//
// Milkyway Hierarchical Verilog Dump:
// Generated on 12/19/2022 at 22:37:25
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :floating_MAC_16.mw
// Cell Name    :floating_MAC_16
// Hierarchy delimiter:'/'
// Write Command : write_verilog icc_output/floating_MAC_16_extracted.v
//


module floating_add_16_DW01_inc_1 (SUM , A );
output [9:0] SUM ;
input  [9:0] A ;


wire [9:2] carry ;

HADDX1_RVT U1_1_7 (.SO ( SUM[7] ) , .B0 ( carry[7] ) , .A0 ( A[7] ) 
    , .C1 ( carry[8] ) ) ;
HADDX1_RVT U1_1_8 (.SO ( SUM[8] ) , .B0 ( carry[8] ) , .A0 ( A[8] ) 
    , .C1 ( carry[9] ) ) ;
XOR2X1_RVT U2 (.Y ( SUM[9] ) , .A2 ( A[9] ) , .A1 ( carry[9] ) ) ;
INVX1_RVT U1 (.A ( A[0] ) , .Y ( SUM[0] ) ) ;
HADDX1_RVT U1_1_1 (.SO ( SUM[1] ) , .B0 ( A[0] ) , .A0 ( A[1] ) 
    , .C1 ( carry[2] ) ) ;
HADDX1_RVT U1_1_2 (.SO ( SUM[2] ) , .B0 ( carry[2] ) , .A0 ( A[2] ) 
    , .C1 ( carry[3] ) ) ;
HADDX1_RVT U1_1_3 (.SO ( SUM[3] ) , .B0 ( carry[3] ) , .A0 ( A[3] ) 
    , .C1 ( carry[4] ) ) ;
HADDX1_RVT U1_1_4 (.SO ( SUM[4] ) , .B0 ( carry[4] ) , .A0 ( A[4] ) 
    , .C1 ( carry[5] ) ) ;
HADDX1_RVT U1_1_5 (.SO ( SUM[5] ) , .B0 ( carry[5] ) , .A0 ( A[5] ) 
    , .C1 ( carry[6] ) ) ;
HADDX1_RVT U1_1_6 (.SO ( SUM[6] ) , .B0 ( carry[6] ) , .A0 ( A[6] ) 
    , .C1 ( carry[7] ) ) ;
endmodule




module floating_add_16_DW01_inc_0 (SUM , A );
output [9:0] SUM ;
input  [9:0] A ;


wire [9:2] carry ;

HADDX1_RVT U1_1_7 (.SO ( SUM[7] ) , .B0 ( carry[7] ) , .A0 ( A[7] ) 
    , .C1 ( carry[8] ) ) ;
HADDX1_RVT U1_1_8 (.SO ( SUM[8] ) , .B0 ( carry[8] ) , .A0 ( A[8] ) 
    , .C1 ( carry[9] ) ) ;
XOR2X1_RVT U2 (.Y ( SUM[9] ) , .A2 ( A[9] ) , .A1 ( carry[9] ) ) ;
INVX1_RVT U1 (.A ( A[0] ) , .Y ( SUM[0] ) ) ;
HADDX1_RVT U1_1_1 (.SO ( SUM[1] ) , .B0 ( A[0] ) , .A0 ( A[1] ) 
    , .C1 ( carry[2] ) ) ;
HADDX1_RVT U1_1_2 (.SO ( SUM[2] ) , .B0 ( carry[2] ) , .A0 ( A[2] ) 
    , .C1 ( carry[3] ) ) ;
HADDX1_RVT U1_1_3 (.SO ( SUM[3] ) , .B0 ( carry[3] ) , .A0 ( A[3] ) 
    , .C1 ( carry[4] ) ) ;
HADDX1_RVT U1_1_4 (.SO ( SUM[4] ) , .B0 ( carry[4] ) , .A0 ( A[4] ) 
    , .C1 ( carry[5] ) ) ;
HADDX1_RVT U1_1_5 (.SO ( SUM[5] ) , .B0 ( carry[5] ) , .A0 ( A[5] ) 
    , .C1 ( carry[6] ) ) ;
HADDX1_RVT U1_1_6 (.SO ( SUM[6] ) , .B0 ( carry[6] ) , .A0 ( A[6] ) 
    , .C1 ( carry[7] ) ) ;
endmodule




module floating_add_16_DW01_add_1 (SUM , CI , CO , B , A );
output [10:0] SUM ;
input  CI ;
output CO ;
input  [10:0] B ;
input  [10:0] A ;


wire [10:1] carry ;

FADDX1_RVT U1_7 (.CI ( carry[7] ) , .A ( A[7] ) , .CO ( carry[8] ) , .B ( B[7] ) 
    , .S ( SUM[7] ) ) ;
FADDX1_RVT U1_8 (.CI ( carry[8] ) , .A ( A[8] ) , .CO ( carry[9] ) , .B ( B[8] ) 
    , .S ( SUM[8] ) ) ;
FADDX1_RVT U1_9 (.CI ( carry[9] ) , .A ( A[9] ) , .CO ( SUM[10] ) , .B ( B[9] ) 
    , .S ( SUM[9] ) ) ;
AND2X1_RVT U2 (.Y ( carry[1] ) , .A1 ( A[0] ) , .A2 ( B[0] ) ) ;
XOR2X1_RVT U1 (.Y ( SUM[0] ) , .A2 ( B[0] ) , .A1 ( A[0] ) ) ;
FADDX1_RVT U1_1 (.CI ( carry[1] ) , .A ( A[1] ) , .CO ( carry[2] ) , .B ( B[1] ) 
    , .S ( SUM[1] ) ) ;
FADDX1_RVT U1_2 (.CI ( carry[2] ) , .A ( A[2] ) , .CO ( carry[3] ) , .B ( B[2] ) 
    , .S ( SUM[2] ) ) ;
FADDX1_RVT U1_3 (.CI ( carry[3] ) , .A ( A[3] ) , .CO ( carry[4] ) , .B ( B[3] ) 
    , .S ( SUM[3] ) ) ;
FADDX1_RVT U1_4 (.CI ( carry[4] ) , .A ( A[4] ) , .CO ( carry[5] ) , .B ( B[4] ) 
    , .S ( SUM[4] ) ) ;
FADDX1_RVT U1_5 (.CI ( carry[5] ) , .A ( A[5] ) , .CO ( carry[6] ) , .B ( B[5] ) 
    , .S ( SUM[5] ) ) ;
FADDX1_RVT U1_6 (.CI ( carry[6] ) , .A ( A[6] ) , .CO ( carry[7] ) , .B ( B[6] ) 
    , .S ( SUM[6] ) ) ;
endmodule




module floating_add_16_DW01_add_0 (SUM , CI , CO , B , A );
output [10:0] SUM ;
input  CI ;
output CO ;
input  [10:0] B ;
input  [10:0] A ;


wire [10:1] carry ;

FADDX1_RVT U1_7 (.CI ( carry[7] ) , .A ( A[7] ) , .CO ( carry[8] ) , .B ( B[7] ) 
    , .S ( SUM[7] ) ) ;
FADDX1_RVT U1_8 (.CI ( carry[8] ) , .A ( A[8] ) , .CO ( carry[9] ) , .B ( B[8] ) 
    , .S ( SUM[8] ) ) ;
FADDX1_RVT U1_9 (.CI ( carry[9] ) , .A ( A[9] ) , .CO ( SUM[10] ) , .B ( B[9] ) 
    , .S ( SUM[9] ) ) ;
AND2X1_RVT U2 (.Y ( carry[1] ) , .A1 ( A[0] ) , .A2 ( B[0] ) ) ;
XOR2X1_RVT U1 (.Y ( SUM[0] ) , .A2 ( B[0] ) , .A1 ( A[0] ) ) ;
FADDX1_RVT U1_1 (.CI ( carry[1] ) , .A ( A[1] ) , .CO ( carry[2] ) , .B ( B[1] ) 
    , .S ( SUM[1] ) ) ;
FADDX1_RVT U1_2 (.CI ( carry[2] ) , .A ( A[2] ) , .CO ( carry[3] ) , .B ( B[2] ) 
    , .S ( SUM[2] ) ) ;
FADDX1_RVT U1_3 (.CI ( carry[3] ) , .A ( A[3] ) , .CO ( carry[4] ) , .B ( B[3] ) 
    , .S ( SUM[3] ) ) ;
FADDX1_RVT U1_4 (.CI ( carry[4] ) , .A ( A[4] ) , .CO ( carry[5] ) , .B ( B[4] ) 
    , .S ( SUM[4] ) ) ;
FADDX1_RVT U1_5 (.CI ( carry[5] ) , .A ( A[5] ) , .CO ( carry[6] ) , .B ( B[5] ) 
    , .S ( SUM[5] ) ) ;
FADDX1_RVT U1_6 (.CI ( carry[6] ) , .A ( A[6] ) , .CO ( carry[7] ) , .B ( B[6] ) 
    , .S ( SUM[6] ) ) ;
endmodule




module floating_add_16 (data_out , CLK , RESETn , sign_in , data_in_02 , 
    data_in_01 );
output [15:0] data_out ;
input  CLK ;
input  RESETn ;
input  sign_in ;
input  [15:0] data_in_02 ;
input  [16:0] data_in_01 ;

wire [9:0] frac_01 ;
wire [9:0] frac_02 ;

wire [6:0] expo_temp_in ;
wire [6:0] expo_02 ;
wire [6:0] expo_01 ;
wire [10:0] frac_temp_in ;


floating_add_16_DW01_inc_1 add_0_root_add_143_ni (
    .SUM ( {N60 , N59 , N58 , N57 , N56 , N55 , N54 , N53 , N52 , N51 } ) , 
    .A ( {N41 , N42 , N43 , N44 , N45 , N46 , N47 , N48 , N49 , N50 } ) ) ;


floating_add_16_DW01_inc_0 add_0_root_add_138_ni (
    .SUM ( {N29 , N28 , N27 , N26 , N25 , N24 , N23 , N22 , N21 , N20 } ) , 
    .A ( {N10 , N11 , N12 , N13 , N14 , N15 , N16 , N17 , N18 , N19 } ) ) ;


floating_add_16_DW01_add_1 add_157 (
    .SUM ( {N101 , N100 , N99 , N98 , N97 , N96 , N95 , N94 , N93 , N92 , 
	N91 } ) , 
    .CI ( 1'b0 ), 
    .B ( {1'b0, N90 , N89 , N88 , N87 , N86 , N85 , N84 , N83 , N82 , 
	N81 } ) , 
    .A ( {1'b0, frac_01[9] , frac_01[8] , frac_01[7] , frac_01[6] , 
	frac_01[5] , frac_01[4] , frac_01[3] , frac_01[2] , frac_01[1] , 
	frac_01[0] } ) ) ;


floating_add_16_DW01_add_0 add_161 (
    .SUM ( {N129 , N128 , N127 , N126 , N125 , N124 , N123 , N122 , N121 , 
	N120 , N119 } ) , 
    .CI ( 1'b0 ), 
    .B ( {1'b0, N118 , N117 , N116 , N115 , N114 , N113 , N112 , N111 , 
	N110 , N109 } ) , 
    .A ( {1'b0, frac_02[9] , frac_02[8] , frac_02[7] , frac_02[6] , 
	frac_02[5] , frac_02[4] , frac_02[3] , frac_02[2] , frac_02[1] , 
	frac_02[0] } ) ) ;

AND2X1_RVT U154 (.Y ( n89 ) , .A1 ( n12 ) , .A2 ( n61 ) ) ;
MUX21X1_RVT U155 (.A1 ( n68 ) , .S0 ( N77 ) , .Y ( n69 ) , .A2 ( n89 ) ) ;
AND2X1_RVT U156 (.Y ( N81 ) , .A1 ( n69 ) , .A2 ( n91 ) ) ;
MUX21X1_RVT U157 (.A1 ( frac_02[2] ) , .S0 ( n3 ) , .Y ( n70 ) 
    , .A2 ( frac_02[1] ) ) ;
MUX21X1_RVT U158 (.A1 ( frac_02[8] ) , .S0 ( n3 ) , .Y ( n80 ) 
    , .A2 ( frac_02[7] ) ) ;
MUX21X1_RVT U159 (.A1 ( n71 ) , .S0 ( N76 ) , .Y ( n72 ) , .A2 ( n86 ) ) ;
AND2X1_RVT U160 (.Y ( n90 ) , .A1 ( n10 ) , .A2 ( n61 ) ) ;
MUX21X1_RVT U161 (.A1 ( n72 ) , .S0 ( N77 ) , .Y ( n73 ) , .A2 ( n90 ) ) ;
AND2X1_RVT U162 (.Y ( N82 ) , .A1 ( n73 ) , .A2 ( n91 ) ) ;
MUX21X1_RVT U163 (.A1 ( n14 ) , .S0 ( n62 ) , .Y ( n76 ) , .A2 ( n13 ) ) ;
MUX21X1_RVT U164 (.A1 ( n76 ) , .S0 ( N76 ) , .Y ( n77 ) , .A2 ( n7 ) ) ;
AND3X1_RVT U165 (.A1 ( n91 ) , .Y ( N83 ) , .A2 ( n60 ) , .A3 ( n77 ) ) ;
MUX21X1_RVT U166 (.A1 ( n82 ) , .S0 ( N76 ) , .Y ( n83 ) , .A2 ( n88 ) ) ;
AND3X1_RVT U167 (.A1 ( n91 ) , .Y ( N84 ) , .A2 ( n60 ) , .A3 ( n83 ) ) ;
AND3X1_RVT U168 (.A1 ( n91 ) , .Y ( N85 ) , .A2 ( n60 ) , .A3 ( n85 ) ) ;
AND3X1_RVT U169 (.A1 ( n91 ) , .Y ( N86 ) , .A2 ( n60 ) , .A3 ( n87 ) ) ;
AND4X1_RVT U170 (.Y ( N87 ) , .A1 ( n91 ) , .A3 ( n61 ) , .A4 ( n60 ) 
    , .A2 ( n7 ) ) ;
AND4X1_RVT U171 (.Y ( N88 ) , .A1 ( n91 ) , .A3 ( n61 ) , .A4 ( n60 ) 
    , .A2 ( n88 ) ) ;
AND3X1_RVT U172 (.A1 ( n91 ) , .Y ( N89 ) , .A2 ( n60 ) , .A3 ( n89 ) ) ;
AND3X1_RVT U173 (.A1 ( n91 ) , .Y ( N90 ) , .A2 ( n60 ) , .A3 ( n90 ) ) ;
MUX21X1_RVT U174 (.A1 ( frac_01[3] ) , .S0 ( n2 ) , .Y ( n100 ) 
    , .A2 ( frac_01[2] ) ) ;
MUX21X1_RVT U175 (.A1 ( frac_01[1] ) , .S0 ( n2 ) , .Y ( n92 ) 
    , .A2 ( frac_01[0] ) ) ;
MUX21X1_RVT U176 (.A1 ( n100 ) , .S0 ( n65 ) , .Y ( n93 ) , .A2 ( n92 ) ) ;
MUX21X1_RVT U177 (.A1 ( frac_01[5] ) , .S0 ( n2 ) , .Y ( n101 ) 
    , .A2 ( frac_01[4] ) ) ;
MUX21X1_RVT U178 (.A1 ( n93 ) , .S0 ( N104 ) , .Y ( n94 ) , .A2 ( n111 ) ) ;
MUX21X1_RVT U179 (.A1 ( frac_01[9] ) , .S0 ( n2 ) , .Y ( n102 ) 
    , .A2 ( frac_01[8] ) ) ;
AND2X1_RVT U180 (.Y ( n116 ) , .A1 ( n11 ) , .A2 ( n64 ) ) ;
MUX21X1_RVT U181 (.A1 ( n94 ) , .S0 ( N105 ) , .Y ( n95 ) , .A2 ( n116 ) ) ;
AND2X1_RVT U182 (.Y ( N109 ) , .A1 ( n95 ) , .A2 ( n118 ) ) ;
MUX21X1_RVT U183 (.A1 ( frac_01[4] ) , .S0 ( n2 ) , .Y ( n105 ) 
    , .A2 ( frac_01[3] ) ) ;
MUX21X1_RVT U184 (.A1 ( frac_01[2] ) , .S0 ( n2 ) , .Y ( n96 ) 
    , .A2 ( frac_01[1] ) ) ;
MUX21X1_RVT U185 (.A1 ( n105 ) , .S0 ( n65 ) , .Y ( n97 ) , .A2 ( n96 ) ) ;
MUX21X1_RVT U186 (.A1 ( frac_01[8] ) , .S0 ( n2 ) , .Y ( n107 ) 
    , .A2 ( frac_01[7] ) ) ;
MUX21X1_RVT U187 (.A1 ( frac_01[6] ) , .S0 ( n2 ) , .Y ( n106 ) 
    , .A2 ( frac_01[5] ) ) ;
MUX21X1_RVT U188 (.A1 ( n107 ) , .S0 ( n65 ) , .Y ( n113 ) , .A2 ( n106 ) ) ;
AND2X1_RVT U189 (.Y ( n117 ) , .A1 ( n9 ) , .A2 ( n64 ) ) ;
MUX21X1_RVT U190 (.A1 ( n98 ) , .S0 ( N105 ) , .Y ( n99 ) , .A2 ( n117 ) ) ;
AND2X1_RVT U191 (.Y ( N110 ) , .A1 ( n99 ) , .A2 ( n118 ) ) ;
MUX21X1_RVT U192 (.A1 ( n101 ) , .S0 ( n65 ) , .Y ( n103 ) , .A2 ( n100 ) ) ;
AND3X1_RVT U193 (.A1 ( n118 ) , .Y ( N111 ) , .A2 ( n63 ) , .A3 ( n104 ) ) ;
MUX21X1_RVT U194 (.A1 ( n106 ) , .S0 ( n65 ) , .Y ( n109 ) , .A2 ( n105 ) ) ;
AND3X1_RVT U195 (.A1 ( n118 ) , .Y ( N112 ) , .A2 ( n63 ) , .A3 ( n110 ) ) ;
MUX21X1_RVT U196 (.A1 ( n111 ) , .S0 ( N104 ) , .Y ( n112 ) , .A2 ( n11 ) ) ;
AND3X1_RVT U197 (.A1 ( n118 ) , .Y ( N113 ) , .A2 ( n63 ) , .A3 ( n112 ) ) ;
MUX21X1_RVT U198 (.A1 ( n113 ) , .S0 ( N104 ) , .Y ( n114 ) , .A2 ( n9 ) ) ;
AND3X1_RVT U199 (.A1 ( n118 ) , .Y ( N114 ) , .A2 ( n63 ) , .A3 ( n114 ) ) ;
AND4X1_RVT U200 (.Y ( N115 ) , .A1 ( n118 ) , .A3 ( n64 ) , .A4 ( n63 ) 
    , .A2 ( n8 ) ) ;
AND4X1_RVT U201 (.Y ( N116 ) , .A1 ( n118 ) , .A3 ( n64 ) , .A4 ( n63 ) 
    , .A2 ( n115 ) ) ;
AND3X1_RVT U202 (.A1 ( n118 ) , .Y ( N117 ) , .A2 ( n63 ) , .A3 ( n116 ) ) ;
AND3X1_RVT U203 (.A1 ( n118 ) , .Y ( N118 ) , .A2 ( n63 ) , .A3 ( n117 ) ) ;
AND2X1_RVT U204 (.Y ( N176 ) , .A1 ( expo_temp_in[5] ) , .A2 ( n37 ) ) ;
INVX1_RVT U4 (.A ( n27 ) , .Y ( n81 ) ) ;
MUX21X1_RVT U5 (.A1 ( n19 ) , .S0 ( n65 ) , .Y ( n111 ) , .A2 ( n101 ) ) ;
XOR2X1_RVT U6 (.Y ( n2 ) , .A2 ( expo_02[0] ) , .A1 ( n45 ) ) ;
XOR2X1_RVT U8 (.Y ( n3 ) , .A2 ( expo_01[0] ) , .A1 ( n40 ) ) ;
NOR2X1_RVT U9 (.Y ( n5 ) , .A2 ( \sub_157/carry[5] ) , .A1 ( expo_01[5] ) ) ;
NAND2X0_RVT U11 (.A2 ( \sub_161/carry[5] ) , .A1 ( n50 ) , .Y ( n6 ) ) ;
MUX21X1_RVT U12 (.A1 ( n84 ) , .S0 ( N76 ) , .Y ( n85 ) , .A2 ( n12 ) ) ;
MUX21X1_RVT U13 (.A1 ( n67 ) , .S0 ( N76 ) , .Y ( n68 ) , .A2 ( n84 ) ) ;
INVX1_RVT U14 (.A ( n109 ) , .Y ( n21 ) ) ;
INVX1_RVT U15 (.A ( n107 ) , .Y ( n23 ) ) ;
MUX21X1_RVT U16 (.A1 ( n75 ) , .S0 ( n62 ) , .Y ( n7 ) , .A2 ( n74 ) ) ;
INVX1_RVT U48 (.A ( n24 ) , .Y ( n88 ) ) ;
INVX1_RVT U57 (.A ( n80 ) , .Y ( n25 ) ) ;
MUX21X1_RVT U69 (.A1 ( n102 ) , .S0 ( n65 ) , .Y ( n8 ) , .A2 ( n19 ) ) ;
INVX1_RVT U75 (.A ( N103 ) , .Y ( n65 ) ) ;
NOR3X0_RVT U76 (.Y ( n118 ) , .A1 ( n6 ) , .A3 ( N106 ) , .A2 ( N107 ) ) ;
INVX1_RVT U77 (.A ( N75 ) , .Y ( n62 ) ) ;
AND2X1_RVT U78 (.Y ( n9 ) , .A1 ( n108 ) , .A2 ( n65 ) ) ;
AND2X1_RVT U79 (.Y ( n10 ) , .A1 ( n81 ) , .A2 ( n62 ) ) ;
AND2X1_RVT U80 (.Y ( n11 ) , .A1 ( n102 ) , .A2 ( n65 ) ) ;
AND2X1_RVT U81 (.Y ( n12 ) , .A1 ( n75 ) , .A2 ( n62 ) ) ;
MUX21X1_RVT U82 (.A1 ( n103 ) , .S0 ( N104 ) , .Y ( n104 ) , .A2 ( n8 ) ) ;
MUX21X1_RVT U83 (.A1 ( n79 ) , .S0 ( n62 ) , .Y ( n82 ) , .A2 ( n78 ) ) ;
MUX21X1_RVT U84 (.A1 ( frac_02[4] ) , .S0 ( n3 ) , .Y ( n78 ) 
    , .A2 ( frac_02[3] ) ) ;
MUX21X1_RVT U85 (.A1 ( frac_02[6] ) , .S0 ( n3 ) , .Y ( n79 ) 
    , .A2 ( frac_02[5] ) ) ;
MUX21X1_RVT U86 (.A1 ( n86 ) , .S0 ( N76 ) , .Y ( n87 ) , .A2 ( n10 ) ) ;
INVX1_RVT U87 (.A ( n20 ) , .Y ( n110 ) ) ;
MUX21X1_RVT U88 (.A1 ( n97 ) , .S0 ( N104 ) , .Y ( n98 ) , .A2 ( n113 ) ) ;
MUX21X1_RVT U89 (.A1 ( n80 ) , .S0 ( n62 ) , .Y ( n86 ) , .A2 ( n18 ) ) ;
MUX21X1_RVT U90 (.A1 ( n78 ) , .S0 ( n62 ) , .Y ( n71 ) , .A2 ( n70 ) ) ;
MUX21X1_RVT U91 (.A1 ( frac_02[3] ) , .S0 ( n3 ) , .Y ( n13 ) 
    , .A2 ( frac_02[2] ) ) ;
MUX21X1_RVT U92 (.A1 ( frac_02[5] ) , .S0 ( n3 ) , .Y ( n14 ) 
    , .A2 ( frac_02[4] ) ) ;
INVX1_RVT U93 (.A ( n22 ) , .Y ( n115 ) ) ;
NOR3X0_RVT U94 (.Y ( n91 ) , .A1 ( n5 ) , .A3 ( N78 ) , .A2 ( N79 ) ) ;
OAI22X1_RVT U95 (.Y ( n15 ) , .A4 ( n57 ) , .A3 ( n44 ) , .A2 ( n58 ) 
    , .A1 ( n59 ) ) ;
INVX1_RVT U96 (.A ( n15 ) , .Y ( N72 ) ) ;
AND2X1_RVT U97 (.Y ( n35 ) , .A1 ( n16 ) , .A2 ( n17 ) ) ;
XNOR2X1_RVT U98 (.A2 ( sign_01 ) , .A1 ( n33 ) , .Y ( N71 ) ) ;
MUX21X1_RVT U105 (.A1 ( frac_02[6] ) , .S0 ( n3 ) , .Y ( n18 ) 
    , .A2 ( frac_02[5] ) ) ;
MUX21X1_RVT U106 (.A1 ( frac_01[7] ) , .S0 ( n2 ) , .Y ( n19 ) 
    , .A2 ( frac_01[6] ) ) ;
MUX21X1_RVT U107 (.A1 ( n22 ) , .S0 ( n64 ) , .Y ( n20 ) , .A2 ( n21 ) ) ;
MUX21X1_RVT U108 (.A1 ( n26 ) , .S0 ( n65 ) , .Y ( n22 ) , .A2 ( n23 ) ) ;
MUX21X1_RVT U109 (.A1 ( n27 ) , .S0 ( n62 ) , .Y ( n24 ) , .A2 ( n25 ) ) ;
NAND2X0_RVT U110 (.A2 ( n2 ) , .A1 ( frac_01[9] ) , .Y ( n26 ) ) ;
NAND2X0_RVT U111 (.A2 ( n3 ) , .A1 ( frac_02[9] ) , .Y ( n27 ) ) ;
XNOR2X1_RVT U112 (.A2 ( expo_01[5] ) , .A1 ( \sub_157/carry[5] ) , .Y ( N79 ) ) ;
OR2X1_RVT U113 (.Y ( \sub_157/carry[1] ) , .A2 ( n40 ) , .A1 ( expo_01[0] ) ) ;
XOR2X1_RVT U114 (.Y ( N107 ) , .A2 ( \sub_161/carry[5] ) , .A1 ( n50 ) ) ;
OR2X1_RVT U115 (.Y ( \sub_161/carry[1] ) , .A2 ( n45 ) , .A1 ( expo_02[0] ) ) ;
INVX1_RVT U116 (.A ( data_in_02[0] ) , .Y ( N50 ) ) ;
INVX1_RVT U117 (.A ( data_in_02[1] ) , .Y ( N49 ) ) ;
INVX1_RVT U118 (.A ( data_in_02[2] ) , .Y ( N48 ) ) ;
INVX1_RVT U119 (.A ( data_in_02[3] ) , .Y ( N47 ) ) ;
INVX1_RVT U120 (.A ( data_in_02[4] ) , .Y ( N46 ) ) ;
INVX1_RVT U121 (.A ( data_in_02[5] ) , .Y ( N45 ) ) ;
INVX1_RVT U122 (.A ( data_in_02[6] ) , .Y ( N44 ) ) ;
INVX1_RVT U123 (.A ( data_in_02[7] ) , .Y ( N43 ) ) ;
INVX1_RVT U124 (.A ( data_in_02[8] ) , .Y ( N42 ) ) ;
INVX1_RVT U125 (.A ( data_in_02[9] ) , .Y ( N41 ) ) ;
INVX1_RVT U126 (.A ( data_in_01[0] ) , .Y ( N19 ) ) ;
INVX1_RVT U127 (.A ( data_in_01[1] ) , .Y ( N18 ) ) ;
INVX1_RVT U128 (.A ( data_in_01[2] ) , .Y ( N17 ) ) ;
INVX1_RVT U129 (.A ( data_in_01[3] ) , .Y ( N16 ) ) ;
INVX1_RVT U130 (.A ( data_in_01[4] ) , .Y ( N15 ) ) ;
INVX1_RVT U131 (.A ( data_in_01[5] ) , .Y ( N14 ) ) ;
INVX1_RVT U132 (.A ( data_in_01[6] ) , .Y ( N13 ) ) ;
INVX1_RVT U133 (.A ( data_in_01[7] ) , .Y ( N12 ) ) ;
INVX1_RVT U134 (.A ( data_in_01[8] ) , .Y ( N11 ) ) ;
INVX1_RVT U135 (.A ( data_in_01[9] ) , .Y ( N10 ) ) ;
AO21X1_RVT U136 (.A1 ( expo_01[4] ) , .Y ( n59 ) , .A2 ( n44 ) 
    , .A3 ( expo_01[5] ) ) ;
AND2X1_RVT U137 (.Y ( n52 ) , .A1 ( expo_01[3] ) , .A2 ( n43 ) ) ;
OR2X1_RVT U138 (.Y ( n51 ) , .A2 ( expo_01[2] ) , .A1 ( n52 ) ) ;
OA22X1_RVT U139 (.Y ( n56 ) , .A4 ( n51 ) , .A3 ( n42 ) , .A2 ( n43 ) 
    , .A1 ( expo_01[3] ) ) ;
AO21X1_RVT U140 (.A1 ( expo_01[2] ) , .Y ( n55 ) , .A2 ( n42 ) , .A3 ( n52 ) ) ;
AO22X1_RVT U141 (.A2 ( n40 ) , .A3 ( expo_01[1] ) , .Y ( n53 ) , .A4 ( n41 ) 
    , .A1 ( expo_01[0] ) ) ;
OA21X1_RVT U142 (.Y ( n54 ) , .A3 ( n53 ) , .A2 ( n41 ) , .A1 ( expo_01[1] ) ) ;
AO22X1_RVT U143 (.A2 ( n55 ) , .A3 ( n54 ) , .Y ( n58 ) , .A4 ( n56 ) 
    , .A1 ( n56 ) ) ;
OR2X1_RVT U144 (.Y ( n57 ) , .A2 ( expo_01[5] ) , .A1 ( expo_01[4] ) ) ;
INVX1_RVT U145 (.A ( N77 ) , .Y ( n60 ) ) ;
INVX1_RVT U146 (.A ( N76 ) , .Y ( n61 ) ) ;
INVX1_RVT U147 (.A ( N105 ) , .Y ( n63 ) ) ;
INVX1_RVT U148 (.A ( N104 ) , .Y ( n64 ) ) ;
MUX21X1_RVT U149 (.A1 ( frac_02[1] ) , .S0 ( n3 ) , .Y ( n66 ) 
    , .A2 ( frac_02[0] ) ) ;
MUX21X1_RVT U150 (.A1 ( n13 ) , .S0 ( n62 ) , .Y ( n67 ) , .A2 ( n66 ) ) ;
MUX21X1_RVT U151 (.A1 ( frac_02[7] ) , .S0 ( n3 ) , .Y ( n74 ) 
    , .A2 ( frac_02[6] ) ) ;
MUX21X1_RVT U152 (.A1 ( n74 ) , .S0 ( n62 ) , .Y ( n84 ) , .A2 ( n14 ) ) ;
MUX21X1_RVT U153 (.A1 ( frac_02[9] ) , .S0 ( n3 ) , .Y ( n75 ) 
    , .A2 ( frac_02[8] ) ) ;
AO22X1_RVT U53 (.A2 ( n36 ) , .A3 ( expo_temp_in[0] ) , .Y ( N171 ) 
    , .A4 ( n37 ) , .A1 ( expo_temp_in[1] ) ) ;
AND2X1_RVT U54 (.Y ( n37 ) , .A1 ( frac_temp_in[10] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U55 (.Y ( N170 ) , .A1 ( expo_temp_in[0] ) , .A2 ( n36 ) ) ;
AND2X1_RVT U56 (.Y ( n36 ) , .A1 ( n35 ) , .A2 ( n34 ) ) ;
AO22X1_RVT U58 (.A2 ( n15 ) , .A3 ( N72 ) , .Y ( N147 ) , .A4 ( N101 ) 
    , .A1 ( N129 ) ) ;
AO22X1_RVT U59 (.A2 ( n15 ) , .A3 ( N100 ) , .Y ( N146 ) , .A4 ( N72 ) 
    , .A1 ( N128 ) ) ;
AO22X1_RVT U60 (.A2 ( N72 ) , .A3 ( N127 ) , .Y ( N145 ) , .A4 ( n15 ) 
    , .A1 ( N99 ) ) ;
AO22X1_RVT U61 (.A2 ( N72 ) , .A3 ( N126 ) , .Y ( N144 ) , .A4 ( n15 ) 
    , .A1 ( N98 ) ) ;
AO22X1_RVT U62 (.A2 ( N72 ) , .A3 ( N125 ) , .Y ( N143 ) , .A4 ( n15 ) 
    , .A1 ( N97 ) ) ;
AO22X1_RVT U63 (.A2 ( N72 ) , .A3 ( N124 ) , .Y ( N142 ) , .A4 ( n15 ) 
    , .A1 ( N96 ) ) ;
AO22X1_RVT U64 (.A2 ( N72 ) , .A3 ( N123 ) , .Y ( N141 ) , .A4 ( n15 ) 
    , .A1 ( N95 ) ) ;
AO22X1_RVT U65 (.A2 ( N72 ) , .A3 ( N122 ) , .Y ( N140 ) , .A4 ( n15 ) 
    , .A1 ( N94 ) ) ;
AO22X1_RVT U66 (.A2 ( N72 ) , .A3 ( N121 ) , .Y ( N139 ) , .A4 ( n15 ) 
    , .A1 ( N93 ) ) ;
AO22X1_RVT U67 (.A2 ( N72 ) , .A3 ( N120 ) , .Y ( N138 ) , .A4 ( n15 ) 
    , .A1 ( N92 ) ) ;
AO22X1_RVT U68 (.A2 ( N72 ) , .A3 ( N119 ) , .Y ( N137 ) , .A4 ( n15 ) 
    , .A1 ( N91 ) ) ;
AO22X1_RVT U70 (.A2 ( N72 ) , .A3 ( expo_02[4] ) , .Y ( N134 ) , .A4 ( n15 ) 
    , .A1 ( expo_01[4] ) ) ;
AO22X1_RVT U71 (.A2 ( N72 ) , .A3 ( expo_02[3] ) , .Y ( N133 ) , .A4 ( n15 ) 
    , .A1 ( expo_01[3] ) ) ;
AO22X1_RVT U72 (.A2 ( N72 ) , .A3 ( expo_02[2] ) , .Y ( N132 ) , .A4 ( n15 ) 
    , .A1 ( expo_01[2] ) ) ;
AO22X1_RVT U73 (.A2 ( N72 ) , .A3 ( expo_02[1] ) , .Y ( N131 ) , .A4 ( n15 ) 
    , .A1 ( expo_01[1] ) ) ;
AO22X1_RVT U74 (.A2 ( N72 ) , .A3 ( expo_02[0] ) , .Y ( N130 ) , .A4 ( n15 ) 
    , .A1 ( expo_01[0] ) ) ;
FADDX1_RVT \sub_161/U2_1 (.CI ( \sub_161/carry[1] ) , .A ( expo_02[1] ) 
    , .CO ( \sub_161/carry[2] ) , .B ( n46 ) , .S ( N103 ) ) ;
FADDX1_RVT \sub_161/U2_2 (.CI ( \sub_161/carry[2] ) , .A ( expo_02[2] ) 
    , .CO ( \sub_161/carry[3] ) , .B ( n47 ) , .S ( N104 ) ) ;
FADDX1_RVT \sub_161/U2_3 (.CI ( \sub_161/carry[3] ) , .A ( expo_02[3] ) 
    , .CO ( \sub_161/carry[4] ) , .B ( n48 ) , .S ( N105 ) ) ;
FADDX1_RVT \sub_161/U2_4 (.CI ( \sub_161/carry[4] ) , .A ( expo_02[4] ) 
    , .CO ( \sub_161/carry[5] ) , .B ( n49 ) , .S ( N106 ) ) ;
FADDX1_RVT \sub_157/U2_1 (.CI ( \sub_157/carry[1] ) , .A ( expo_01[1] ) 
    , .CO ( \sub_157/carry[2] ) , .B ( n41 ) , .S ( N75 ) ) ;
FADDX1_RVT \sub_157/U2_2 (.CI ( \sub_157/carry[2] ) , .A ( expo_01[2] ) 
    , .CO ( \sub_157/carry[3] ) , .B ( n42 ) , .S ( N76 ) ) ;
FADDX1_RVT \sub_157/U2_3 (.CI ( \sub_157/carry[3] ) , .A ( expo_01[3] ) 
    , .CO ( \sub_157/carry[4] ) , .B ( n43 ) , .S ( N77 ) ) ;
FADDX1_RVT \sub_157/U2_4 (.CI ( \sub_157/carry[4] ) , .A ( expo_01[4] ) 
    , .CO ( \sub_157/carry[5] ) , .B ( n44 ) , .S ( N78 ) ) ;
DFFARX1_RVT \expo_02_reg[4] (.QN ( n44 ) , .RSTB ( RESETn ) 
    , .D ( data_in_02[14] ) , .CLK ( CLK ) , .Q ( expo_02[4] ) ) ;
DFFARX1_RVT \expo_02_reg[3] (.QN ( n43 ) , .RSTB ( RESETn ) 
    , .D ( data_in_02[13] ) , .CLK ( CLK ) , .Q ( expo_02[3] ) ) ;
DFFARX1_RVT \expo_02_reg[2] (.QN ( n42 ) , .RSTB ( RESETn ) 
    , .D ( data_in_02[12] ) , .CLK ( CLK ) , .Q ( expo_02[2] ) ) ;
DFFARX1_RVT \expo_02_reg[1] (.QN ( n41 ) , .RSTB ( RESETn ) 
    , .D ( data_in_02[11] ) , .CLK ( CLK ) , .Q ( expo_02[1] ) ) ;
DFFARX1_RVT \expo_02_reg[0] (.QN ( n40 ) , .RSTB ( RESETn ) 
    , .D ( data_in_02[10] ) , .CLK ( CLK ) , .Q ( expo_02[0] ) ) ;
DFFARX1_RVT \expo_01_reg[5] (.QN ( n50 ) , .RSTB ( RESETn ) 
    , .D ( data_in_01[15] ) , .CLK ( CLK ) , .Q ( expo_01[5] ) ) ;
DFFARX1_RVT \expo_01_reg[4] (.QN ( n49 ) , .RSTB ( RESETn ) 
    , .D ( data_in_01[14] ) , .CLK ( CLK ) , .Q ( expo_01[4] ) ) ;
DFFARX1_RVT \expo_01_reg[3] (.QN ( n48 ) , .RSTB ( RESETn ) 
    , .D ( data_in_01[13] ) , .CLK ( CLK ) , .Q ( expo_01[3] ) ) ;
DFFARX1_RVT \expo_01_reg[2] (.QN ( n47 ) , .RSTB ( RESETn ) 
    , .D ( data_in_01[12] ) , .CLK ( CLK ) , .Q ( expo_01[2] ) ) ;
DFFARX1_RVT \expo_01_reg[1] (.QN ( n46 ) , .RSTB ( RESETn ) 
    , .D ( data_in_01[11] ) , .CLK ( CLK ) , .Q ( expo_01[1] ) ) ;
DFFARX1_RVT \expo_01_reg[0] (.QN ( n45 ) , .RSTB ( RESETn ) 
    , .D ( data_in_01[10] ) , .CLK ( CLK ) , .Q ( expo_01[0] ) ) ;
DFFARX1_RVT \frac_02_reg[0] (.RSTB ( RESETn ) , .D ( N61 ) , .CLK ( CLK ) 
    , .Q ( frac_02[0] ) ) ;
DFFARX1_RVT sign_out_reg (.RSTB ( RESETn ) , .D ( N187 ) , .CLK ( CLK ) 
    , .Q ( data_out[15] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[9] (.RSTB ( RESETn ) , .D ( N186 ) , .CLK ( CLK ) 
    , .Q ( data_out[9] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[8] (.RSTB ( RESETn ) , .D ( N185 ) , .CLK ( CLK ) 
    , .Q ( data_out[8] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[7] (.RSTB ( RESETn ) , .D ( N184 ) , .CLK ( CLK ) 
    , .Q ( data_out[7] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[6] (.RSTB ( RESETn ) , .D ( N183 ) , .CLK ( CLK ) 
    , .Q ( data_out[6] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[5] (.RSTB ( RESETn ) , .D ( N182 ) , .CLK ( CLK ) 
    , .Q ( data_out[5] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[4] (.RSTB ( RESETn ) , .D ( N181 ) , .CLK ( CLK ) 
    , .Q ( data_out[4] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[3] (.RSTB ( RESETn ) , .D ( N180 ) , .CLK ( CLK ) 
    , .Q ( data_out[3] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[2] (.RSTB ( RESETn ) , .D ( N179 ) , .CLK ( CLK ) 
    , .Q ( data_out[2] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[1] (.RSTB ( RESETn ) , .D ( N178 ) , .CLK ( CLK ) 
    , .Q ( data_out[1] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[0] (.RSTB ( RESETn ) , .D ( N177 ) , .CLK ( CLK ) 
    , .Q ( data_out[0] ) ) ;
DFFARX1_RVT \frac_01_reg[0] (.RSTB ( RESETn ) , .D ( N30 ) , .CLK ( CLK ) 
    , .Q ( frac_01[0] ) ) ;
DFFARX1_RVT \frac_02_reg[1] (.RSTB ( RESETn ) , .D ( N62 ) , .CLK ( CLK ) 
    , .Q ( frac_02[1] ) ) ;
DFFARX1_RVT sign_temp_reg (.RSTB ( RESETn ) , .D ( N71 ) , .CLK ( CLK ) 
    , .Q ( sign_temp ) ) ;
DFFARX1_RVT \expo_temp_out_reg[0] (.RSTB ( RESETn ) , .D ( N170 ) , .CLK ( CLK ) 
    , .Q ( data_out[10] ) ) ;
DFFARX1_RVT \frac_01_reg[1] (.RSTB ( RESETn ) , .D ( N31 ) , .CLK ( CLK ) 
    , .Q ( frac_01[1] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[4] (.RSTB ( RESETn ) , .D ( N174 ) , .CLK ( CLK ) 
    , .Q ( data_out[14] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[3] (.RSTB ( RESETn ) , .D ( N173 ) , .CLK ( CLK ) 
    , .Q ( data_out[13] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[2] (.RSTB ( RESETn ) , .D ( N172 ) , .CLK ( CLK ) 
    , .Q ( data_out[12] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[1] (.RSTB ( RESETn ) , .D ( N171 ) , .CLK ( CLK ) 
    , .Q ( data_out[11] ) ) ;
DFFARX1_RVT \frac_02_reg[2] (.RSTB ( RESETn ) , .D ( N63 ) , .CLK ( CLK ) 
    , .Q ( frac_02[2] ) ) ;
DFFARX1_RVT \frac_01_reg[2] (.RSTB ( RESETn ) , .D ( N32 ) , .CLK ( CLK ) 
    , .Q ( frac_01[2] ) ) ;
DFFARX1_RVT \frac_02_reg[3] (.RSTB ( RESETn ) , .D ( N64 ) , .CLK ( CLK ) 
    , .Q ( frac_02[3] ) ) ;
DFFARX1_RVT \frac_01_reg[3] (.RSTB ( RESETn ) , .D ( N33 ) , .CLK ( CLK ) 
    , .Q ( frac_01[3] ) ) ;
DFFARX1_RVT \frac_02_reg[4] (.RSTB ( RESETn ) , .D ( N65 ) , .CLK ( CLK ) 
    , .Q ( frac_02[4] ) ) ;
DFFARX1_RVT \frac_01_reg[4] (.RSTB ( RESETn ) , .D ( N34 ) , .CLK ( CLK ) 
    , .Q ( frac_01[4] ) ) ;
DFFARX1_RVT \frac_02_reg[5] (.RSTB ( RESETn ) , .D ( N66 ) , .CLK ( CLK ) 
    , .Q ( frac_02[5] ) ) ;
DFFARX1_RVT \frac_01_reg[5] (.RSTB ( RESETn ) , .D ( N35 ) , .CLK ( CLK ) 
    , .Q ( frac_01[5] ) ) ;
DFFARX1_RVT \frac_02_reg[6] (.RSTB ( RESETn ) , .D ( N67 ) , .CLK ( CLK ) 
    , .Q ( frac_02[6] ) ) ;
DFFARX1_RVT \frac_01_reg[6] (.RSTB ( RESETn ) , .D ( N36 ) , .CLK ( CLK ) 
    , .Q ( frac_01[6] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[5] (.RSTB ( RESETn ) , .D ( expo_01[5] ) 
    , .CLK ( CLK ) , .Q ( expo_temp_in[5] ) ) ;
DFFARX1_RVT \frac_02_reg[7] (.RSTB ( RESETn ) , .D ( N68 ) , .CLK ( CLK ) 
    , .Q ( frac_02[7] ) ) ;
DFFARX1_RVT \frac_01_reg[7] (.RSTB ( RESETn ) , .D ( N37 ) , .CLK ( CLK ) 
    , .Q ( frac_01[7] ) ) ;
DFFARX1_RVT \frac_02_reg[8] (.RSTB ( RESETn ) , .D ( N69 ) , .CLK ( CLK ) 
    , .Q ( frac_02[8] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[4] (.RSTB ( RESETn ) , .D ( N134 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[4] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[3] (.RSTB ( RESETn ) , .D ( N133 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[3] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[2] (.RSTB ( RESETn ) , .D ( N132 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[2] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[1] (.RSTB ( RESETn ) , .D ( N131 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[1] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[0] (.RSTB ( RESETn ) , .D ( N130 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[0] ) ) ;
DFFARX1_RVT \frac_01_reg[8] (.RSTB ( RESETn ) , .D ( N38 ) , .CLK ( CLK ) 
    , .Q ( frac_01[8] ) ) ;
DFFARX1_RVT \frac_02_reg[9] (.RSTB ( RESETn ) , .D ( N70 ) , .CLK ( CLK ) 
    , .Q ( frac_02[9] ) ) ;
DFFARX1_RVT \frac_01_reg[9] (.RSTB ( RESETn ) , .D ( N39 ) , .CLK ( CLK ) 
    , .Q ( frac_01[9] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[0] (.RSTB ( RESETn ) , .D ( N137 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[0] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[1] (.RSTB ( RESETn ) , .D ( N138 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[1] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[2] (.RSTB ( RESETn ) , .D ( N139 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[2] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[3] (.RSTB ( RESETn ) , .D ( N140 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[3] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[4] (.RSTB ( RESETn ) , .D ( N141 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[4] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[5] (.RSTB ( RESETn ) , .D ( N142 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[5] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[6] (.RSTB ( RESETn ) , .D ( N143 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[6] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[7] (.RSTB ( RESETn ) , .D ( N144 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[7] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[8] (.RSTB ( RESETn ) , .D ( N145 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[8] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[9] (.RSTB ( RESETn ) , .D ( N146 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[9] ) ) ;
INVX1_RVT U3 (.A ( n26 ) , .Y ( n108 ) ) ;
DFFARX1_RVT sign_01_reg (.QN ( n32 ) , .RSTB ( RESETn ) , .D ( sign_in ) 
    , .CLK ( CLK ) , .Q ( sign_01 ) ) ;
DFFARX1_RVT sign_02_reg (.QN ( n33 ) , .RSTB ( RESETn ) , .D ( data_in_02[15] ) 
    , .CLK ( CLK ) , .Q ( sign_02 ) ) ;
DFFARX1_RVT \frac_temp_in_reg[10] (.QN ( n34 ) , .RSTB ( RESETn ) , .D ( N147 ) 
    , .CLK ( CLK ) , .Q ( frac_temp_in[10] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[5] (.QN ( n17 ) , .RSTB ( RESETn ) , .D ( N175 ) 
    , .CLK ( CLK ) ) ;
DFFARX1_RVT \expo_temp_out_reg[6] (.QN ( n16 ) , .RSTB ( RESETn ) , .D ( N176 ) 
    , .CLK ( CLK ) ) ;
AO22X1_RVT U17 (.A2 ( n33 ) , .A3 ( N60 ) , .Y ( N70 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[9] ) ) ;
AO22X1_RVT U18 (.A2 ( n33 ) , .A3 ( N59 ) , .Y ( N69 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[8] ) ) ;
AO22X1_RVT U19 (.A2 ( n33 ) , .A3 ( N58 ) , .Y ( N68 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[7] ) ) ;
AO22X1_RVT U20 (.A2 ( n33 ) , .A3 ( N57 ) , .Y ( N67 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[6] ) ) ;
AO22X1_RVT U21 (.A2 ( n33 ) , .A3 ( N56 ) , .Y ( N66 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[5] ) ) ;
AO22X1_RVT U22 (.A2 ( n33 ) , .A3 ( N55 ) , .Y ( N65 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[4] ) ) ;
AO22X1_RVT U23 (.A2 ( n33 ) , .A3 ( N54 ) , .Y ( N64 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[3] ) ) ;
AO22X1_RVT U24 (.A2 ( n33 ) , .A3 ( N53 ) , .Y ( N63 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[2] ) ) ;
AO22X1_RVT U25 (.A2 ( n33 ) , .A3 ( N52 ) , .Y ( N62 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[1] ) ) ;
AO22X1_RVT U26 (.A2 ( n33 ) , .A3 ( N51 ) , .Y ( N61 ) , .A4 ( sign_02 ) 
    , .A1 ( data_in_02[0] ) ) ;
AO22X1_RVT U27 (.A2 ( n32 ) , .A3 ( N29 ) , .Y ( N39 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[9] ) ) ;
AO22X1_RVT U28 (.A2 ( n32 ) , .A3 ( N28 ) , .Y ( N38 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[8] ) ) ;
AO22X1_RVT U29 (.A2 ( n32 ) , .A3 ( N27 ) , .Y ( N37 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[7] ) ) ;
AO22X1_RVT U30 (.A2 ( n32 ) , .A3 ( N26 ) , .Y ( N36 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[6] ) ) ;
AO22X1_RVT U31 (.A2 ( n32 ) , .A3 ( N25 ) , .Y ( N35 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[5] ) ) ;
AO22X1_RVT U32 (.A2 ( n32 ) , .A3 ( N24 ) , .Y ( N34 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[4] ) ) ;
AO22X1_RVT U33 (.A2 ( n32 ) , .A3 ( N23 ) , .Y ( N33 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[3] ) ) ;
AO22X1_RVT U34 (.A2 ( n32 ) , .A3 ( N22 ) , .Y ( N32 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[2] ) ) ;
AO22X1_RVT U35 (.A2 ( n32 ) , .A3 ( N21 ) , .Y ( N31 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[1] ) ) ;
AO22X1_RVT U36 (.A2 ( n32 ) , .A3 ( N20 ) , .Y ( N30 ) , .A4 ( sign_01 ) 
    , .A1 ( data_in_01[0] ) ) ;
AND2X1_RVT U37 (.Y ( N187 ) , .A1 ( sign_temp ) , .A2 ( n35 ) ) ;
AND2X1_RVT U38 (.Y ( N186 ) , .A1 ( frac_temp_in[9] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U39 (.Y ( N185 ) , .A1 ( frac_temp_in[8] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U40 (.Y ( N184 ) , .A1 ( frac_temp_in[7] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U41 (.Y ( N183 ) , .A1 ( frac_temp_in[6] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U42 (.Y ( N182 ) , .A1 ( frac_temp_in[5] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U43 (.Y ( N181 ) , .A1 ( frac_temp_in[4] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U44 (.Y ( N180 ) , .A1 ( frac_temp_in[3] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U45 (.Y ( N179 ) , .A1 ( frac_temp_in[2] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U46 (.Y ( N178 ) , .A1 ( frac_temp_in[1] ) , .A2 ( n35 ) ) ;
AND2X1_RVT U47 (.Y ( N177 ) , .A1 ( frac_temp_in[0] ) , .A2 ( n35 ) ) ;
AO22X1_RVT U49 (.A2 ( expo_temp_in[5] ) , .A3 ( expo_temp_in[4] ) , .Y ( N175 ) 
    , .A4 ( n37 ) , .A1 ( n36 ) ) ;
AO22X1_RVT U50 (.A2 ( n36 ) , .A3 ( expo_temp_in[3] ) , .Y ( N174 ) 
    , .A4 ( n37 ) , .A1 ( expo_temp_in[4] ) ) ;
AO22X1_RVT U51 (.A2 ( n36 ) , .A3 ( expo_temp_in[2] ) , .Y ( N173 ) 
    , .A4 ( n37 ) , .A1 ( expo_temp_in[3] ) ) ;
AO22X1_RVT U52 (.A2 ( n36 ) , .A3 ( expo_temp_in[1] ) , .Y ( N172 ) 
    , .A4 ( n37 ) , .A1 ( expo_temp_in[2] ) ) ;
endmodule




module floating_mul_16_DW_mult_uns_0 (product , b , a );
output [19:0] product ;
input  [9:0] b ;
input  [9:0] a ;



FADDX1_RVT U4 (.CI ( n4 ) , .A ( n22 ) , .CO ( n3 ) , .B ( n25 ) 
    , .S ( product[16] ) ) ;
FADDX1_RVT U3 (.CI ( n3 ) , .A ( n20 ) , .CO ( n2 ) , .B ( n21 ) 
    , .S ( product[17] ) ) ;
FADDX1_RVT U2 (.CI ( n2 ) , .A ( n163 ) , .CO ( product[19] ) , .B ( n19 ) 
    , .S ( product[18] ) ) ;
FADDX1_RVT U21 (.CI ( n27 ) , .A ( n29 ) , .CO ( n21 ) , .B ( n24 ) , .S ( n22 ) ) ;
FADDX1_RVT U20 (.CI ( n23 ) , .A ( n173 ) , .CO ( n19 ) , .B ( n164 ) 
    , .S ( n20 ) ) ;
FADDX1_RVT U10 (.CI ( n10 ) , .A ( n91 ) , .CO ( n9 ) , .B ( n76 ) 
    , .S ( product[10] ) ) ;
FADDX1_RVT U9 (.CI ( n9 ) , .A ( n75 ) , .CO ( n8 ) , .B ( n62 ) 
    , .S ( product[11] ) ) ;
FADDX1_RVT U8 (.CI ( n8 ) , .A ( n61 ) , .CO ( n7 ) , .B ( n50 ) 
    , .S ( product[12] ) ) ;
FADDX1_RVT U7 (.CI ( n7 ) , .A ( n49 ) , .CO ( n6 ) , .B ( n40 ) 
    , .S ( product[13] ) ) ;
FADDX1_RVT U6 (.CI ( n6 ) , .A ( n39 ) , .CO ( n5 ) , .B ( n32 ) 
    , .S ( product[14] ) ) ;
FADDX1_RVT U5 (.CI ( n5 ) , .A ( n31 ) , .CO ( n4 ) , .B ( n26 ) 
    , .S ( product[15] ) ) ;
FADDX1_RVT U29 (.CI ( n176 ) , .A ( n203 ) , .CO ( n37 ) , .B ( n167 ) 
    , .S ( n38 ) ) ;
FADDX1_RVT U28 (.CI ( n47 ) , .A ( n194 ) , .CO ( n35 ) , .B ( n185 ) 
    , .S ( n36 ) ) ;
FADDX1_RVT U27 (.CI ( n43 ) , .A ( n45 ) , .CO ( n33 ) , .B ( n38 ) , .S ( n34 ) ) ;
FADDX1_RVT U26 (.CI ( n34 ) , .A ( n36 ) , .CO ( n31 ) , .B ( n41 ) , .S ( n32 ) ) ;
FADDX1_RVT U25 (.CI ( n175 ) , .A ( n193 ) , .CO ( n29 ) , .B ( n166 ) 
    , .S ( n30 ) ) ;
FADDX1_RVT U24 (.CI ( n30 ) , .A ( n184 ) , .CO ( n27 ) , .B ( n37 ) , .S ( n28 ) ) ;
FADDX1_RVT U23 (.CI ( n33 ) , .A ( n35 ) , .CO ( n25 ) , .B ( n28 ) , .S ( n26 ) ) ;
FADDX1_RVT U22 (.CI ( n174 ) , .A ( n183 ) , .CO ( n23 ) , .B ( n165 ) 
    , .S ( n24 ) ) ;
FADDX1_RVT U37 (.CI ( n69 ) , .A ( n58 ) , .CO ( n53 ) , .B ( n60 ) , .S ( n54 ) ) ;
FADDX1_RVT U36 (.CI ( n65 ) , .A ( n67 ) , .CO ( n51 ) , .B ( n56 ) , .S ( n52 ) ) ;
FADDX1_RVT U35 (.CI ( n52 ) , .A ( n54 ) , .CO ( n49 ) , .B ( n63 ) , .S ( n50 ) ) ;
FADDX1_RVT U34 (.CI ( n177 ) , .A ( n213 ) , .CO ( n47 ) , .B ( n168 ) 
    , .S ( n48 ) ) ;
FADDX1_RVT U33 (.CI ( n204 ) , .A ( n186 ) , .CO ( n45 ) , .B ( n195 ) 
    , .S ( n46 ) ) ;
FADDX1_RVT U32 (.CI ( n46 ) , .A ( n59 ) , .CO ( n43 ) , .B ( n57 ) , .S ( n44 ) ) ;
FADDX1_RVT U31 (.CI ( n53 ) , .A ( n48 ) , .CO ( n41 ) , .B ( n55 ) , .S ( n42 ) ) ;
FADDX1_RVT U30 (.CI ( n42 ) , .A ( n44 ) , .CO ( n39 ) , .B ( n51 ) , .S ( n40 ) ) ;
FADDX1_RVT U45 (.CI ( n89 ) , .A ( n215 ) , .CO ( n69 ) , .B ( n206 ) 
    , .S ( n70 ) ) ;
FADDX1_RVT U44 (.CI ( n72 ) , .A ( n87 ) , .CO ( n67 ) , .B ( n85 ) , .S ( n68 ) ) ;
FADDX1_RVT U43 (.CI ( n70 ) , .A ( n74 ) , .CO ( n65 ) , .B ( n83 ) , .S ( n66 ) ) ;
FADDX1_RVT U42 (.CI ( n79 ) , .A ( n81 ) , .CO ( n63 ) , .B ( n68 ) , .S ( n64 ) ) ;
FADDX1_RVT U41 (.CI ( n64 ) , .A ( n66 ) , .CO ( n61 ) , .B ( n77 ) , .S ( n62 ) ) ;
FADDX1_RVT U40 (.CI ( n178 ) , .A ( n223 ) , .CO ( n59 ) , .B ( n169 ) 
    , .S ( n60 ) ) ;
FADDX1_RVT U39 (.CI ( n205 ) , .A ( n187 ) , .CO ( n57 ) , .B ( n214 ) 
    , .S ( n58 ) ) ;
FADDX1_RVT U38 (.CI ( n71 ) , .A ( n196 ) , .CO ( n55 ) , .B ( n73 ) , .S ( n56 ) ) ;
FADDX1_RVT U53 (.CI ( n198 ) , .A ( n225 ) , .CO ( n85 ) , .B ( n189 ) 
    , .S ( n86 ) ) ;
FADDX1_RVT U52 (.CI ( n90 ) , .A ( n216 ) , .CO ( n83 ) , .B ( n105 ) 
    , .S ( n84 ) ) ;
FADDX1_RVT U51 (.CI ( n86 ) , .A ( n103 ) , .CO ( n81 ) , .B ( n101 ) 
    , .S ( n82 ) ) ;
FADDX1_RVT U50 (.CI ( n97 ) , .A ( n88 ) , .CO ( n79 ) , .B ( n99 ) , .S ( n80 ) ) ;
FADDX1_RVT U49 (.CI ( n82 ) , .A ( n84 ) , .CO ( n77 ) , .B ( n95 ) , .S ( n78 ) ) ;
FADDX1_RVT U48 (.CI ( n78 ) , .A ( n93 ) , .CO ( n75 ) , .B ( n80 ) , .S ( n76 ) ) ;
FADDX1_RVT U47 (.CI ( n179 ) , .A ( n233 ) , .CO ( n73 ) , .B ( n170 ) 
    , .S ( n74 ) ) ;
FADDX1_RVT U46 (.CI ( n197 ) , .A ( n224 ) , .CO ( n71 ) , .B ( n188 ) 
    , .S ( n72 ) ) ;
FADDX1_RVT U61 (.CI ( n217 ) , .A ( n208 ) , .CO ( n101 ) , .B ( n199 ) 
    , .S ( n102 ) ) ;
FADDX1_RVT U60 (.CI ( n119 ) , .A ( n235 ) , .CO ( n99 ) , .B ( n226 ) 
    , .S ( n100 ) ) ;
FADDX1_RVT U59 (.CI ( n115 ) , .A ( n106 ) , .CO ( n97 ) , .B ( n117 ) 
    , .S ( n98 ) ) ;
FADDX1_RVT U58 (.CI ( n113 ) , .A ( n102 ) , .CO ( n95 ) , .B ( n104 ) 
    , .S ( n96 ) ) ;
FADDX1_RVT U57 (.CI ( n98 ) , .A ( n100 ) , .CO ( n93 ) , .B ( n111 ) 
    , .S ( n94 ) ) ;
FADDX1_RVT U56 (.CI ( n94 ) , .A ( n109 ) , .CO ( n91 ) , .B ( n96 ) , .S ( n92 ) ) ;
HADDX1_RVT U55 (.SO ( n90 ) , .B0 ( n171 ) , .A0 ( n180 ) , .C1 ( n89 ) ) ;
FADDX1_RVT U54 (.CI ( n234 ) , .A ( n207 ) , .CO ( n87 ) , .B ( n243 ) 
    , .S ( n88 ) ) ;
FADDX1_RVT U69 (.CI ( n245 ) , .A ( n254 ) , .CO ( n117 ) , .B ( n200 ) 
    , .S ( n118 ) ) ;
FADDX1_RVT U68 (.CI ( n209 ) , .A ( n218 ) , .CO ( n115 ) , .B ( n236 ) 
    , .S ( n116 ) ) ;
FADDX1_RVT U67 (.CI ( n120 ) , .A ( n227 ) , .CO ( n113 ) , .B ( n131 ) 
    , .S ( n114 ) ) ;
FADDX1_RVT U66 (.CI ( n116 ) , .A ( n129 ) , .CO ( n111 ) , .B ( n127 ) 
    , .S ( n112 ) ) ;
FADDX1_RVT U65 (.CI ( n114 ) , .A ( n118 ) , .CO ( n109 ) , .B ( n125 ) 
    , .S ( n110 ) ) ;
FADDX1_RVT U64 (.CI ( n110 ) , .A ( n123 ) , .CO ( n107 ) , .B ( n112 ) 
    , .S ( n108 ) ) ;
HADDX1_RVT U63 (.SO ( n106 ) , .B0 ( n172 ) , .A0 ( n181 ) , .C1 ( n105 ) ) ;
FADDX1_RVT U62 (.CI ( n244 ) , .A ( n253 ) , .CO ( n103 ) , .B ( n190 ) 
    , .S ( n104 ) ) ;
FADDX1_RVT U77 (.CI ( n136 ) , .A ( n145 ) , .CO ( n133 ) , .B ( n138 ) 
    , .S ( n134 ) ) ;
HADDX1_RVT U76 (.SO ( n132 ) , .B0 ( n192 ) , .A0 ( n201 ) , .C1 ( n131 ) ) ;
FADDX1_RVT U75 (.CI ( n246 ) , .A ( n255 ) , .CO ( n129 ) , .B ( n210 ) 
    , .S ( n130 ) ) ;
FADDX1_RVT U74 (.CI ( n228 ) , .A ( n237 ) , .CO ( n127 ) , .B ( n219 ) 
    , .S ( n128 ) ) ;
FADDX1_RVT U73 (.CI ( n139 ) , .A ( n141 ) , .CO ( n125 ) , .B ( n132 ) 
    , .S ( n126 ) ) ;
FADDX1_RVT U72 (.CI ( n137 ) , .A ( n128 ) , .CO ( n123 ) , .B ( n130 ) 
    , .S ( n124 ) ) ;
FADDX1_RVT U71 (.CI ( n124 ) , .A ( n135 ) , .CO ( n121 ) , .B ( n126 ) 
    , .S ( n122 ) ) ;
HADDX1_RVT U70 (.SO ( n120 ) , .B0 ( n182 ) , .A0 ( n191 ) , .C1 ( n119 ) ) ;
HADDX1_RVT U85 (.SO ( n150 ) , .B0 ( n212 ) , .A0 ( n221 ) , .C1 ( n149 ) ) ;
FADDX1_RVT U84 (.CI ( n239 ) , .A ( n257 ) , .CO ( n147 ) , .B ( n230 ) 
    , .S ( n148 ) ) ;
FADDX1_RVT U83 (.CI ( n150 ) , .A ( n248 ) , .CO ( n145 ) , .B ( n155 ) 
    , .S ( n146 ) ) ;
FADDX1_RVT U82 (.CI ( n146 ) , .A ( n153 ) , .CO ( n143 ) , .B ( n148 ) 
    , .S ( n144 ) ) ;
HADDX1_RVT U81 (.SO ( n142 ) , .B0 ( n202 ) , .A0 ( n211 ) , .C1 ( n141 ) ) ;
FADDX1_RVT U80 (.CI ( n247 ) , .A ( n256 ) , .CO ( n139 ) , .B ( n220 ) 
    , .S ( n140 ) ) ;
FADDX1_RVT U79 (.CI ( n149 ) , .A ( n238 ) , .CO ( n137 ) , .B ( n229 ) 
    , .S ( n138 ) ) ;
FADDX1_RVT U78 (.CI ( n140 ) , .A ( n142 ) , .CO ( n135 ) , .B ( n147 ) 
    , .S ( n136 ) ) ;
AND2X1_RVT U214 (.Y ( n259 ) , .A1 ( b[3] ) , .A2 ( a[0] ) ) ;
AND2X1_RVT U213 (.Y ( n260 ) , .A1 ( b[2] ) , .A2 ( a[0] ) ) ;
HADDX1_RVT U91 (.SO ( n162 ) , .B0 ( n251 ) , .A0 ( n260 ) , .C1 ( n161 ) ) ;
HADDX1_RVT U90 (.SO ( n160 ) , .B0 ( n232 ) , .A0 ( n241 ) , .C1 ( n159 ) ) ;
FADDX1_RVT U89 (.CI ( n161 ) , .A ( n259 ) , .CO ( n157 ) , .B ( n250 ) 
    , .S ( n158 ) ) ;
HADDX1_RVT U88 (.SO ( n156 ) , .B0 ( n222 ) , .A0 ( n231 ) , .C1 ( n155 ) ) ;
FADDX1_RVT U87 (.CI ( n249 ) , .A ( n258 ) , .CO ( n153 ) , .B ( n240 ) 
    , .S ( n154 ) ) ;
FADDX1_RVT U86 (.CI ( n154 ) , .A ( n159 ) , .CO ( n151 ) , .B ( n156 ) 
    , .S ( n152 ) ) ;
AND2X1_RVT U222 (.Y ( n250 ) , .A1 ( a[1] ) , .A2 ( b[2] ) ) ;
AND2X1_RVT U221 (.Y ( n251 ) , .A1 ( b[1] ) , .A2 ( a[1] ) ) ;
AND2X1_RVT U220 (.Y ( n253 ) , .A1 ( b[9] ) , .A2 ( a[0] ) ) ;
AND2X1_RVT U219 (.Y ( n254 ) , .A1 ( b[8] ) , .A2 ( a[0] ) ) ;
AND2X1_RVT U218 (.Y ( n255 ) , .A1 ( b[7] ) , .A2 ( a[0] ) ) ;
AND2X1_RVT U217 (.Y ( n256 ) , .A1 ( b[6] ) , .A2 ( a[0] ) ) ;
AND2X1_RVT U216 (.Y ( n257 ) , .A1 ( b[5] ) , .A2 ( a[0] ) ) ;
AND2X1_RVT U215 (.Y ( n258 ) , .A1 ( b[4] ) , .A2 ( a[0] ) ) ;
AND2X1_RVT U230 (.Y ( n241 ) , .A1 ( a[2] ) , .A2 ( b[1] ) ) ;
AND2X1_RVT U229 (.Y ( n243 ) , .A1 ( a[1] ) , .A2 ( b[9] ) ) ;
AND2X1_RVT U228 (.Y ( n244 ) , .A1 ( a[1] ) , .A2 ( b[8] ) ) ;
AND2X1_RVT U227 (.Y ( n245 ) , .A1 ( a[1] ) , .A2 ( b[7] ) ) ;
AND2X1_RVT U226 (.Y ( n246 ) , .A1 ( a[1] ) , .A2 ( b[6] ) ) ;
AND2X1_RVT U225 (.Y ( n247 ) , .A1 ( a[1] ) , .A2 ( b[5] ) ) ;
AND2X1_RVT U224 (.Y ( n248 ) , .A1 ( a[1] ) , .A2 ( b[4] ) ) ;
AND2X1_RVT U223 (.Y ( n249 ) , .A1 ( a[1] ) , .A2 ( b[3] ) ) ;
AND2X1_RVT U238 (.Y ( n233 ) , .A1 ( a[2] ) , .A2 ( b[9] ) ) ;
AND2X1_RVT U237 (.Y ( n234 ) , .A1 ( a[2] ) , .A2 ( b[8] ) ) ;
AND2X1_RVT U236 (.Y ( n235 ) , .A1 ( a[2] ) , .A2 ( b[7] ) ) ;
AND2X1_RVT U235 (.Y ( n236 ) , .A1 ( a[2] ) , .A2 ( b[6] ) ) ;
AND2X1_RVT U234 (.Y ( n237 ) , .A1 ( a[2] ) , .A2 ( b[5] ) ) ;
AND2X1_RVT U233 (.Y ( n238 ) , .A1 ( a[2] ) , .A2 ( b[4] ) ) ;
AND2X1_RVT U232 (.Y ( n239 ) , .A1 ( a[2] ) , .A2 ( b[3] ) ) ;
AND2X1_RVT U231 (.Y ( n240 ) , .A1 ( a[2] ) , .A2 ( b[2] ) ) ;
AND2X1_RVT U246 (.Y ( n225 ) , .A1 ( a[3] ) , .A2 ( b[7] ) ) ;
AND2X1_RVT U245 (.Y ( n226 ) , .A1 ( a[3] ) , .A2 ( b[6] ) ) ;
AND2X1_RVT U244 (.Y ( n227 ) , .A1 ( a[3] ) , .A2 ( b[5] ) ) ;
AND2X1_RVT U243 (.Y ( n228 ) , .A1 ( a[3] ) , .A2 ( b[4] ) ) ;
AND2X1_RVT U242 (.Y ( n229 ) , .A1 ( a[3] ) , .A2 ( b[3] ) ) ;
AND2X1_RVT U241 (.Y ( n230 ) , .A1 ( a[3] ) , .A2 ( b[2] ) ) ;
AND2X1_RVT U240 (.Y ( n231 ) , .A1 ( a[3] ) , .A2 ( b[1] ) ) ;
AND2X1_RVT U239 (.Y ( n232 ) , .A1 ( b[0] ) , .A2 ( a[3] ) ) ;
AND2X1_RVT U254 (.Y ( n217 ) , .A1 ( a[4] ) , .A2 ( b[5] ) ) ;
AND2X1_RVT U253 (.Y ( n218 ) , .A1 ( a[4] ) , .A2 ( b[4] ) ) ;
AND2X1_RVT U252 (.Y ( n219 ) , .A1 ( a[4] ) , .A2 ( b[3] ) ) ;
AND2X1_RVT U251 (.Y ( n220 ) , .A1 ( a[4] ) , .A2 ( b[2] ) ) ;
AND2X1_RVT U250 (.Y ( n221 ) , .A1 ( a[4] ) , .A2 ( b[1] ) ) ;
AND2X1_RVT U249 (.Y ( n222 ) , .A1 ( a[4] ) , .A2 ( b[0] ) ) ;
AND2X1_RVT U248 (.Y ( n223 ) , .A1 ( a[3] ) , .A2 ( b[9] ) ) ;
AND2X1_RVT U247 (.Y ( n224 ) , .A1 ( a[3] ) , .A2 ( b[8] ) ) ;
AND2X1_RVT U262 (.Y ( n209 ) , .A1 ( a[5] ) , .A2 ( b[3] ) ) ;
AND2X1_RVT U261 (.Y ( n210 ) , .A1 ( a[5] ) , .A2 ( b[2] ) ) ;
AND2X1_RVT U260 (.Y ( n211 ) , .A1 ( a[5] ) , .A2 ( b[1] ) ) ;
AND2X1_RVT U259 (.Y ( n212 ) , .A1 ( a[5] ) , .A2 ( b[0] ) ) ;
AND2X1_RVT U258 (.Y ( n213 ) , .A1 ( a[4] ) , .A2 ( b[9] ) ) ;
AND2X1_RVT U257 (.Y ( n214 ) , .A1 ( a[4] ) , .A2 ( b[8] ) ) ;
AND2X1_RVT U256 (.Y ( n215 ) , .A1 ( a[4] ) , .A2 ( b[7] ) ) ;
AND2X1_RVT U255 (.Y ( n216 ) , .A1 ( a[4] ) , .A2 ( b[6] ) ) ;
AND2X1_RVT U270 (.Y ( n201 ) , .A1 ( a[6] ) , .A2 ( b[1] ) ) ;
AND2X1_RVT U269 (.Y ( n202 ) , .A1 ( a[6] ) , .A2 ( b[0] ) ) ;
AND2X1_RVT U268 (.Y ( n203 ) , .A1 ( a[5] ) , .A2 ( b[9] ) ) ;
AND2X1_RVT U267 (.Y ( n204 ) , .A1 ( a[5] ) , .A2 ( b[8] ) ) ;
AND2X1_RVT U266 (.Y ( n205 ) , .A1 ( a[5] ) , .A2 ( b[7] ) ) ;
AND2X1_RVT U265 (.Y ( n206 ) , .A1 ( a[5] ) , .A2 ( b[6] ) ) ;
AND2X1_RVT U264 (.Y ( n207 ) , .A1 ( a[5] ) , .A2 ( b[5] ) ) ;
AND2X1_RVT U263 (.Y ( n208 ) , .A1 ( a[5] ) , .A2 ( b[4] ) ) ;
AND2X1_RVT U278 (.Y ( n193 ) , .A1 ( a[6] ) , .A2 ( b[9] ) ) ;
AND2X1_RVT U277 (.Y ( n194 ) , .A1 ( a[6] ) , .A2 ( b[8] ) ) ;
AND2X1_RVT U276 (.Y ( n195 ) , .A1 ( a[6] ) , .A2 ( b[7] ) ) ;
AND2X1_RVT U275 (.Y ( n196 ) , .A1 ( a[6] ) , .A2 ( b[6] ) ) ;
AND2X1_RVT U274 (.Y ( n197 ) , .A1 ( a[6] ) , .A2 ( b[5] ) ) ;
AND2X1_RVT U273 (.Y ( n198 ) , .A1 ( a[6] ) , .A2 ( b[4] ) ) ;
AND2X1_RVT U272 (.Y ( n199 ) , .A1 ( a[6] ) , .A2 ( b[3] ) ) ;
AND2X1_RVT U271 (.Y ( n200 ) , .A1 ( a[6] ) , .A2 ( b[2] ) ) ;
AND2X1_RVT U286 (.Y ( n185 ) , .A1 ( a[7] ) , .A2 ( b[7] ) ) ;
AND2X1_RVT U285 (.Y ( n186 ) , .A1 ( a[7] ) , .A2 ( b[6] ) ) ;
AND2X1_RVT U284 (.Y ( n187 ) , .A1 ( a[7] ) , .A2 ( b[5] ) ) ;
AND2X1_RVT U283 (.Y ( n188 ) , .A1 ( a[7] ) , .A2 ( b[4] ) ) ;
AND2X1_RVT U282 (.Y ( n189 ) , .A1 ( a[7] ) , .A2 ( b[3] ) ) ;
AND2X1_RVT U281 (.Y ( n190 ) , .A1 ( a[7] ) , .A2 ( b[2] ) ) ;
AND2X1_RVT U280 (.Y ( n191 ) , .A1 ( a[7] ) , .A2 ( b[1] ) ) ;
AND2X1_RVT U279 (.Y ( n192 ) , .A1 ( a[7] ) , .A2 ( b[0] ) ) ;
AND2X1_RVT U294 (.Y ( n177 ) , .A1 ( a[8] ) , .A2 ( b[5] ) ) ;
AND2X1_RVT U293 (.Y ( n178 ) , .A1 ( a[8] ) , .A2 ( b[4] ) ) ;
AND2X1_RVT U292 (.Y ( n179 ) , .A1 ( a[8] ) , .A2 ( b[3] ) ) ;
AND2X1_RVT U291 (.Y ( n180 ) , .A1 ( a[8] ) , .A2 ( b[2] ) ) ;
AND2X1_RVT U290 (.Y ( n181 ) , .A1 ( a[8] ) , .A2 ( b[1] ) ) ;
AND2X1_RVT U289 (.Y ( n182 ) , .A1 ( a[8] ) , .A2 ( b[0] ) ) ;
AND2X1_RVT U288 (.Y ( n183 ) , .A1 ( a[7] ) , .A2 ( b[9] ) ) ;
AND2X1_RVT U287 (.Y ( n184 ) , .A1 ( a[7] ) , .A2 ( b[8] ) ) ;
AND2X1_RVT U302 (.Y ( n169 ) , .A1 ( a[9] ) , .A2 ( b[3] ) ) ;
AND2X1_RVT U301 (.Y ( n170 ) , .A1 ( a[9] ) , .A2 ( b[2] ) ) ;
AND2X1_RVT U300 (.Y ( n171 ) , .A1 ( a[9] ) , .A2 ( b[1] ) ) ;
AND2X1_RVT U299 (.Y ( n172 ) , .A1 ( a[9] ) , .A2 ( b[0] ) ) ;
AND2X1_RVT U298 (.Y ( n173 ) , .A1 ( a[8] ) , .A2 ( b[9] ) ) ;
AND2X1_RVT U297 (.Y ( n174 ) , .A1 ( a[8] ) , .A2 ( b[8] ) ) ;
AND2X1_RVT U296 (.Y ( n175 ) , .A1 ( a[8] ) , .A2 ( b[7] ) ) ;
AND2X1_RVT U295 (.Y ( n176 ) , .A1 ( a[8] ) , .A2 ( b[6] ) ) ;
AO222X1_RVT U310 (.A1 ( n317 ) , .A5 ( n108 ) , .A6 ( n121 ) , .A3 ( n317 ) 
    , .A2 ( n121 ) , .Y ( n316 ) , .A4 ( n108 ) ) ;
AO222X1_RVT U309 (.A1 ( n316 ) , .A5 ( n92 ) , .A6 ( n107 ) , .A3 ( n316 ) 
    , .A2 ( n107 ) , .Y ( n10 ) , .A4 ( n92 ) ) ;
AND2X1_RVT U308 (.Y ( n163 ) , .A1 ( a[9] ) , .A2 ( b[9] ) ) ;
AND2X1_RVT U307 (.Y ( n164 ) , .A1 ( a[9] ) , .A2 ( b[8] ) ) ;
AND2X1_RVT U306 (.Y ( n165 ) , .A1 ( a[9] ) , .A2 ( b[7] ) ) ;
AND2X1_RVT U305 (.Y ( n166 ) , .A1 ( a[9] ) , .A2 ( b[6] ) ) ;
AND2X1_RVT U304 (.Y ( n167 ) , .A1 ( a[9] ) , .A2 ( b[5] ) ) ;
AND2X1_RVT U303 (.Y ( n168 ) , .A1 ( a[9] ) , .A2 ( b[4] ) ) ;
AND2X1_RVT U318 (.Y ( n323 ) , .A1 ( b[0] ) , .A2 ( a[2] ) ) ;
AND4X1_RVT U317 (.Y ( n324 ) , .A1 ( b[0] ) , .A3 ( a[1] ) , .A4 ( a[0] ) 
    , .A2 ( b[1] ) ) ;
AO222X1_RVT U316 (.A1 ( n323 ) , .A5 ( n323 ) , .A6 ( n324 ) , .A3 ( n162 ) 
    , .A2 ( n162 ) , .Y ( n322 ) , .A4 ( n324 ) ) ;
AO222X1_RVT U315 (.A1 ( n158 ) , .A5 ( n322 ) , .A6 ( n160 ) , .A3 ( n322 ) 
    , .A2 ( n160 ) , .Y ( n321 ) , .A4 ( n158 ) ) ;
AO222X1_RVT U314 (.A1 ( n321 ) , .A5 ( n152 ) , .A6 ( n157 ) , .A3 ( n321 ) 
    , .A2 ( n157 ) , .Y ( n320 ) , .A4 ( n152 ) ) ;
AO222X1_RVT U313 (.A1 ( n320 ) , .A5 ( n144 ) , .A6 ( n151 ) , .A3 ( n320 ) 
    , .A2 ( n151 ) , .Y ( n319 ) , .A4 ( n144 ) ) ;
AO222X1_RVT U312 (.A1 ( n319 ) , .A5 ( n134 ) , .A6 ( n143 ) , .A3 ( n319 ) 
    , .A2 ( n143 ) , .Y ( n318 ) , .A4 ( n134 ) ) ;
AO222X1_RVT U311 (.A1 ( n318 ) , .A5 ( n122 ) , .A6 ( n133 ) , .A3 ( n318 ) 
    , .A2 ( n133 ) , .Y ( n317 ) , .A4 ( n122 ) ) ;
endmodule




module floating_mul_16_DW01_add_0 (SUM , CI , CO , B , A );
output [6:0] SUM ;
input  CI ;
output CO ;
input  [6:0] B ;
input  [6:0] A ;


wire [6:1] carry ;

FADDX1_RVT U1_4 (.CI ( carry[4] ) , .A ( A[4] ) , .CO ( carry[5] ) , .B ( B[4] ) 
    , .S ( SUM[4] ) ) ;
AND2X1_RVT U5 (.Y ( carry[1] ) , .A1 ( A[0] ) , .A2 ( B[0] ) ) ;
XOR2X1_RVT U4 (.Y ( SUM[0] ) , .A2 ( B[0] ) , .A1 ( A[0] ) ) ;
NAND2X0_RVT U3 (.A2 ( carry[5] ) , .A1 ( B[5] ) , .Y ( n1 ) ) ;
XNOR2X1_RVT U2 (.A2 ( n1 ) , .A1 ( B[6] ) , .Y ( SUM[6] ) ) ;
XOR2X1_RVT U1 (.Y ( SUM[5] ) , .A2 ( carry[5] ) , .A1 ( B[5] ) ) ;
FADDX1_RVT U1_1 (.CI ( carry[1] ) , .A ( A[1] ) , .CO ( carry[2] ) , .B ( B[1] ) 
    , .S ( SUM[1] ) ) ;
FADDX1_RVT U1_2 (.CI ( carry[2] ) , .A ( A[2] ) , .CO ( carry[3] ) , .B ( B[2] ) 
    , .S ( SUM[2] ) ) ;
FADDX1_RVT U1_3 (.CI ( carry[3] ) , .A ( A[3] ) , .CO ( carry[4] ) , .B ( B[3] ) 
    , .S ( SUM[3] ) ) ;
endmodule




module floating_mul_16 (data_out_03 , CLK , RESETn , sign_out , 
    data_out , data_in_03 , data_in_02 , data_in_01 );
output [15:0] data_out_03 ;
input  CLK ;
input  RESETn ;
output sign_out ;
output [16:0] data_out ;
input  [15:0] data_in_03 ;
input  [15:0] data_in_02 ;
input  [15:0] data_in_01 ;

wire [9:0] frac_02 ;
wire [9:0] frac_01 ;
wire [4:0] expo_01 ;

wire [4:0] expo_02 ;
wire [19:10] frac_temp_in ;
wire [6:0] expo_temp_in ;


floating_mul_16_DW_mult_uns_0 mult_80 (
    .product ( {N28 , N27 , N26 , N25 , N24 , N23 , N22 , N21 , N20 , N19 , 
	SYNOPSYS_UNCONNECTED_0, SYNOPSYS_UNCONNECTED_1, 
	SYNOPSYS_UNCONNECTED_2, SYNOPSYS_UNCONNECTED_3, 
	SYNOPSYS_UNCONNECTED_4, SYNOPSYS_UNCONNECTED_5, 
	SYNOPSYS_UNCONNECTED_6, SYNOPSYS_UNCONNECTED_7, 
	SYNOPSYS_UNCONNECTED_8, SYNOPSYS_UNCONNECTED_9} ) , 
    .b ( frac_02 ) , .a ( frac_01 ) ) ;


floating_mul_16_DW01_add_0 add_0_root_sub_0_root_sub_79 (
    .SUM ( {N18 , N17 , N16 , N15 , N14 , N13 , N12 } ) , .CI ( 1'b0 ), 
    .B ( {n1 , n1 , \sub_1_root_sub_0_root_sub_79/DIFF[4] , 
	\sub_1_root_sub_0_root_sub_79/DIFF[3] , 
	\sub_1_root_sub_0_root_sub_79/DIFF[2] , 
	\sub_1_root_sub_0_root_sub_79/DIFF[1] , n39 } ) , 
    .A ( {1'b0, 1'b0, expo_01[4] , expo_01[3] , expo_01[2] , expo_01[1] , 
	expo_01[0] } ) ) ;

INVX8_RVT U1 (.A ( RESETn ) , .Y ( n3 ) ) ;
DFFARX1_RVT \frac_02_reg[0] (.RSTB ( RESETn ) , .D ( data_in_02[0] ) 
    , .CLK ( CLK ) , .Q ( frac_02[0] ) ) ;
DFFARX1_RVT \frac_01_reg[9] (.RSTB ( RESETn ) , .D ( data_in_01[9] ) 
    , .CLK ( CLK ) , .Q ( frac_01[9] ) ) ;
DFFARX1_RVT \frac_01_reg[8] (.RSTB ( RESETn ) , .D ( data_in_01[8] ) 
    , .CLK ( CLK ) , .Q ( frac_01[8] ) ) ;
DFFARX1_RVT \frac_01_reg[7] (.RSTB ( RESETn ) , .D ( data_in_01[7] ) 
    , .CLK ( CLK ) , .Q ( frac_01[7] ) ) ;
DFFARX1_RVT \frac_01_reg[6] (.RSTB ( RESETn ) , .D ( data_in_01[6] ) 
    , .CLK ( CLK ) , .Q ( frac_01[6] ) ) ;
DFFARX1_RVT \frac_01_reg[5] (.RSTB ( RESETn ) , .D ( data_in_01[5] ) 
    , .CLK ( CLK ) , .Q ( frac_01[5] ) ) ;
DFFARX1_RVT \frac_01_reg[4] (.RSTB ( RESETn ) , .D ( data_in_01[4] ) 
    , .CLK ( CLK ) , .Q ( frac_01[4] ) ) ;
DFFARX1_RVT \frac_01_reg[3] (.RSTB ( RESETn ) , .D ( data_in_01[3] ) 
    , .CLK ( CLK ) , .Q ( frac_01[3] ) ) ;
DFFARX1_RVT \frac_01_reg[2] (.RSTB ( RESETn ) , .D ( data_in_01[2] ) 
    , .CLK ( CLK ) , .Q ( frac_01[2] ) ) ;
DFFARX1_RVT \frac_01_reg[1] (.RSTB ( RESETn ) , .D ( data_in_01[1] ) 
    , .CLK ( CLK ) , .Q ( frac_01[1] ) ) ;
DFFARX1_RVT \frac_01_reg[0] (.RSTB ( RESETn ) , .D ( data_in_01[0] ) 
    , .CLK ( CLK ) , .Q ( frac_01[0] ) ) ;
DFFARX1_RVT \expo_02_reg[4] (.RSTB ( RESETn ) , .D ( data_in_02[14] ) 
    , .CLK ( CLK ) , .Q ( expo_02[4] ) ) ;
DFFARX1_RVT \expo_02_reg[3] (.RSTB ( RESETn ) , .D ( data_in_02[13] ) 
    , .CLK ( CLK ) , .Q ( expo_02[3] ) ) ;
DFFARX1_RVT \expo_02_reg[2] (.RSTB ( RESETn ) , .D ( data_in_02[12] ) 
    , .CLK ( CLK ) , .Q ( expo_02[2] ) ) ;
DFFARX1_RVT \expo_02_reg[1] (.RSTB ( RESETn ) , .D ( data_in_02[11] ) 
    , .CLK ( CLK ) , .Q ( expo_02[1] ) ) ;
DFFARX1_RVT \expo_02_reg[0] (.QN ( n39 ) , .RSTB ( RESETn ) 
    , .D ( data_in_02[10] ) , .CLK ( CLK ) , .Q ( expo_02[0] ) ) ;
DFFARX1_RVT \expo_01_reg[4] (.RSTB ( RESETn ) , .D ( data_in_01[14] ) 
    , .CLK ( CLK ) , .Q ( expo_01[4] ) ) ;
DFFARX1_RVT \expo_01_reg[3] (.RSTB ( RESETn ) , .D ( data_in_01[13] ) 
    , .CLK ( CLK ) , .Q ( expo_01[3] ) ) ;
NOR2X1_RVT U5 (.Y ( n1 ) , .A2 ( \sub_1_root_sub_0_root_sub_79/carry[4] ) 
    , .A1 ( expo_02[4] ) ) ;
AND2X1_RVT U51 (.Y ( n22 ) , .A1 ( n24 ) , .A2 ( n25 ) ) ;
XOR2X1_RVT U70 (.Y ( n23 ) , .A2 ( sign_01 ) , .A1 ( sign_02 ) ) ;
XNOR2X1_RVT U71 (.A2 ( expo_02[4] ) 
    , .A1 ( \sub_1_root_sub_0_root_sub_79/carry[4] ) 
    , .Y ( \sub_1_root_sub_0_root_sub_79/DIFF[4] ) ) ;
AND2X1_RVT U76 (.Y ( \sub_1_root_sub_0_root_sub_79/carry[4] ) 
    , .A1 ( expo_02[3] ) , .A2 ( \sub_1_root_sub_0_root_sub_79/carry[3] ) ) ;
XOR2X1_RVT U77 (.Y ( \sub_1_root_sub_0_root_sub_79/DIFF[3] ) 
    , .A2 ( \sub_1_root_sub_0_root_sub_79/carry[3] ) , .A1 ( expo_02[3] ) ) ;
AND2X1_RVT U78 (.Y ( \sub_1_root_sub_0_root_sub_79/carry[3] ) 
    , .A1 ( expo_02[2] ) , .A2 ( \sub_1_root_sub_0_root_sub_79/carry[2] ) ) ;
XOR2X1_RVT U79 (.Y ( \sub_1_root_sub_0_root_sub_79/DIFF[2] ) 
    , .A2 ( \sub_1_root_sub_0_root_sub_79/carry[2] ) , .A1 ( expo_02[2] ) ) ;
AND2X1_RVT U80 (.Y ( \sub_1_root_sub_0_root_sub_79/carry[2] ) 
    , .A1 ( expo_02[1] ) , .A2 ( expo_02[0] ) ) ;
XOR2X1_RVT U81 (.Y ( \sub_1_root_sub_0_root_sub_79/DIFF[1] ) 
    , .A2 ( expo_02[0] ) , .A1 ( expo_02[1] ) ) ;
AO22X1_RVT U15 (.A2 ( n34 ) , .A3 ( n3 ) , .Y ( n52 ) , .A4 ( data_out_03[4] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U16 (.A2 ( \data_buffer[0][4] ) , .A3 ( n3 ) , .Y ( n53 ) 
    , .A4 ( n34 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U18 (.A2 ( n33 ) , .A3 ( n3 ) , .Y ( n54 ) , .A4 ( data_out_03[5] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U19 (.A2 ( \data_buffer[0][5] ) , .A3 ( n3 ) , .Y ( n55 ) 
    , .A4 ( n33 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U21 (.A2 ( n32 ) , .A3 ( n3 ) , .Y ( n56 ) , .A4 ( data_out_03[6] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U22 (.A2 ( \data_buffer[0][6] ) , .A3 ( n3 ) , .Y ( n57 ) 
    , .A4 ( n32 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U24 (.A2 ( n31 ) , .A3 ( n3 ) , .Y ( n58 ) , .A4 ( data_out_03[7] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U25 (.A2 ( \data_buffer[0][7] ) , .A3 ( n3 ) , .Y ( n59 ) 
    , .A4 ( n31 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U27 (.A2 ( n30 ) , .A3 ( n3 ) , .Y ( n60 ) , .A4 ( data_out_03[8] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U28 (.A2 ( \data_buffer[0][8] ) , .A3 ( n3 ) , .Y ( n61 ) 
    , .A4 ( n30 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U30 (.A2 ( n29 ) , .A3 ( n3 ) , .Y ( n62 ) , .A4 ( data_out_03[9] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U31 (.A2 ( \data_buffer[0][9] ) , .A3 ( n3 ) , .Y ( n63 ) 
    , .A4 ( n29 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U33 (.A2 ( n28 ) , .A3 ( n3 ) , .Y ( n64 ) , .A4 ( data_out_03[10] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U34 (.A2 ( \data_buffer[0][10] ) , .A3 ( n3 ) , .Y ( n65 ) 
    , .A4 ( n28 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U36 (.A2 ( n21 ) , .A3 ( n3 ) , .Y ( n66 ) , .A4 ( data_out_03[11] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U37 (.A2 ( \data_buffer[0][11] ) , .A3 ( n3 ) , .Y ( n67 ) 
    , .A4 ( n21 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U39 (.A2 ( n20 ) , .A3 ( n3 ) , .Y ( n68 ) , .A4 ( data_out_03[12] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U40 (.A2 ( \data_buffer[0][12] ) , .A3 ( n3 ) , .Y ( n69 ) 
    , .A4 ( n20 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U42 (.A2 ( n19 ) , .A3 ( n3 ) , .Y ( n70 ) , .A4 ( data_out_03[13] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U43 (.A2 ( \data_buffer[0][13] ) , .A3 ( n3 ) , .Y ( n71 ) 
    , .A4 ( n19 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U45 (.A2 ( n18 ) , .A3 ( n3 ) , .Y ( n72 ) , .A4 ( data_out_03[14] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U46 (.A2 ( \data_buffer[0][14] ) , .A3 ( n3 ) , .Y ( n73 ) 
    , .A4 ( n18 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U48 (.A2 ( n17 ) , .A3 ( n3 ) , .Y ( n74 ) , .A4 ( data_out_03[15] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U49 (.A2 ( \data_buffer[0][15] ) , .A3 ( n3 ) , .Y ( n75 ) 
    , .A4 ( n17 ) , .A1 ( RESETn ) ) ;
AND2X1_RVT U52 (.Y ( N46 ) , .A1 ( N28 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U53 (.Y ( N45 ) , .A1 ( N27 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U54 (.Y ( N44 ) , .A1 ( N26 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U55 (.Y ( N43 ) , .A1 ( N25 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U56 (.Y ( N42 ) , .A1 ( N24 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U57 (.Y ( N41 ) , .A1 ( N23 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U58 (.Y ( N40 ) , .A1 ( N22 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U59 (.Y ( N39 ) , .A1 ( N21 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U60 (.Y ( N38 ) , .A1 ( N20 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U61 (.Y ( N37 ) , .A1 ( N19 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U63 (.Y ( N35 ) , .A1 ( N17 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U64 (.Y ( N34 ) , .A1 ( N16 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U65 (.Y ( N33 ) , .A1 ( N15 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U66 (.Y ( N32 ) , .A1 ( N14 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U67 (.Y ( N31 ) , .A1 ( N13 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U68 (.Y ( N30 ) , .A1 ( N12 ) , .A2 ( n22 ) ) ;
AND2X1_RVT U69 (.Y ( N29 ) , .A1 ( n22 ) , .A2 ( n23 ) ) ;
OR3X1_RVT U72 (.Y ( n25 ) , .A3 ( n26 ) , .A1 ( expo_02[1] ) 
    , .A2 ( expo_02[0] ) ) ;
OR3X1_RVT U73 (.Y ( n26 ) , .A3 ( expo_02[2] ) , .A1 ( expo_02[4] ) 
    , .A2 ( expo_02[3] ) ) ;
OR3X1_RVT U74 (.Y ( n24 ) , .A3 ( n27 ) , .A1 ( expo_01[1] ) 
    , .A2 ( expo_01[0] ) ) ;
OR3X1_RVT U75 (.Y ( n27 ) , .A3 ( expo_01[2] ) , .A1 ( expo_01[4] ) 
    , .A2 ( expo_01[3] ) ) ;
DFFARX1_RVT sign_temp_out_reg (.RSTB ( RESETn ) , .D ( sign_temp_in ) 
    , .CLK ( CLK ) , .Q ( sign_out ) ) ;
DFFARX1_RVT \frac_temp_out_reg[9] (.RSTB ( RESETn ) , .D ( frac_temp_in[19] ) 
    , .CLK ( CLK ) , .Q ( data_out[9] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[8] (.RSTB ( RESETn ) , .D ( frac_temp_in[18] ) 
    , .CLK ( CLK ) , .Q ( data_out[8] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[7] (.RSTB ( RESETn ) , .D ( frac_temp_in[17] ) 
    , .CLK ( CLK ) , .Q ( data_out[7] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[6] (.RSTB ( RESETn ) , .D ( frac_temp_in[16] ) 
    , .CLK ( CLK ) , .Q ( data_out[6] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[5] (.RSTB ( RESETn ) , .D ( frac_temp_in[15] ) 
    , .CLK ( CLK ) , .Q ( data_out[5] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[4] (.RSTB ( RESETn ) , .D ( frac_temp_in[14] ) 
    , .CLK ( CLK ) , .Q ( data_out[4] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[3] (.RSTB ( RESETn ) , .D ( frac_temp_in[13] ) 
    , .CLK ( CLK ) , .Q ( data_out[3] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[2] (.RSTB ( RESETn ) , .D ( frac_temp_in[12] ) 
    , .CLK ( CLK ) , .Q ( data_out[2] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[1] (.RSTB ( RESETn ) , .D ( frac_temp_in[11] ) 
    , .CLK ( CLK ) , .Q ( data_out[1] ) ) ;
DFFARX1_RVT \frac_temp_out_reg[0] (.RSTB ( RESETn ) , .D ( frac_temp_in[10] ) 
    , .CLK ( CLK ) , .Q ( data_out[0] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[5] (.RSTB ( RESETn ) , .D ( expo_temp_in[5] ) 
    , .CLK ( CLK ) , .Q ( data_out[15] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[4] (.RSTB ( RESETn ) , .D ( expo_temp_in[4] ) 
    , .CLK ( CLK ) , .Q ( data_out[14] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[3] (.RSTB ( RESETn ) , .D ( expo_temp_in[3] ) 
    , .CLK ( CLK ) , .Q ( data_out[13] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[2] (.RSTB ( RESETn ) , .D ( expo_temp_in[2] ) 
    , .CLK ( CLK ) , .Q ( data_out[12] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[1] (.RSTB ( RESETn ) , .D ( expo_temp_in[1] ) 
    , .CLK ( CLK ) , .Q ( data_out[11] ) ) ;
DFFARX1_RVT \expo_temp_out_reg[0] (.RSTB ( RESETn ) , .D ( expo_temp_in[0] ) 
    , .CLK ( CLK ) , .Q ( data_out[10] ) ) ;
DFFARX1_RVT sign_temp_in_reg (.RSTB ( RESETn ) , .D ( N29 ) , .CLK ( CLK ) 
    , .Q ( sign_temp_in ) ) ;
DFFARX1_RVT \expo_temp_in_reg[0] (.RSTB ( RESETn ) , .D ( N30 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[0] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[1] (.RSTB ( RESETn ) , .D ( N31 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[1] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[2] (.RSTB ( RESETn ) , .D ( N32 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[2] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[3] (.RSTB ( RESETn ) , .D ( N33 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[3] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[4] (.RSTB ( RESETn ) , .D ( N34 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[4] ) ) ;
DFFARX1_RVT \expo_temp_in_reg[5] (.RSTB ( RESETn ) , .D ( N35 ) , .CLK ( CLK ) 
    , .Q ( expo_temp_in[5] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[10] (.RSTB ( RESETn ) , .D ( N37 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[10] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[11] (.RSTB ( RESETn ) , .D ( N38 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[11] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[12] (.RSTB ( RESETn ) , .D ( N39 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[12] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[13] (.RSTB ( RESETn ) , .D ( N40 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[13] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[14] (.RSTB ( RESETn ) , .D ( N41 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[14] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[15] (.RSTB ( RESETn ) , .D ( N42 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[15] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[16] (.RSTB ( RESETn ) , .D ( N43 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[16] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[17] (.RSTB ( RESETn ) , .D ( N44 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[17] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[19] (.RSTB ( RESETn ) , .D ( N46 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[19] ) ) ;
DFFARX1_RVT \frac_temp_in_reg[18] (.RSTB ( RESETn ) , .D ( N45 ) , .CLK ( CLK ) 
    , .Q ( frac_temp_in[18] ) ) ;
DFFARX1_RVT sign_02_reg (.RSTB ( RESETn ) , .D ( data_in_02[15] ) 
    , .CLK ( CLK ) , .Q ( sign_02 ) ) ;
DFFARX1_RVT sign_01_reg (.RSTB ( RESETn ) , .D ( data_in_01[15] ) 
    , .CLK ( CLK ) , .Q ( sign_01 ) ) ;
DFFARX1_RVT \frac_02_reg[9] (.RSTB ( RESETn ) , .D ( data_in_02[9] ) 
    , .CLK ( CLK ) , .Q ( frac_02[9] ) ) ;
DFFARX1_RVT \frac_02_reg[8] (.RSTB ( RESETn ) , .D ( data_in_02[8] ) 
    , .CLK ( CLK ) , .Q ( frac_02[8] ) ) ;
DFFARX1_RVT \frac_02_reg[7] (.RSTB ( RESETn ) , .D ( data_in_02[7] ) 
    , .CLK ( CLK ) , .Q ( frac_02[7] ) ) ;
DFFARX1_RVT \frac_02_reg[6] (.RSTB ( RESETn ) , .D ( data_in_02[6] ) 
    , .CLK ( CLK ) , .Q ( frac_02[6] ) ) ;
DFFARX1_RVT \frac_02_reg[5] (.RSTB ( RESETn ) , .D ( data_in_02[5] ) 
    , .CLK ( CLK ) , .Q ( frac_02[5] ) ) ;
DFFARX1_RVT \frac_02_reg[4] (.RSTB ( RESETn ) , .D ( data_in_02[4] ) 
    , .CLK ( CLK ) , .Q ( frac_02[4] ) ) ;
DFFARX1_RVT \frac_02_reg[3] (.RSTB ( RESETn ) , .D ( data_in_02[3] ) 
    , .CLK ( CLK ) , .Q ( frac_02[3] ) ) ;
DFFARX1_RVT \frac_02_reg[2] (.RSTB ( RESETn ) , .D ( data_in_02[2] ) 
    , .CLK ( CLK ) , .Q ( frac_02[2] ) ) ;
DFFARX1_RVT \frac_02_reg[1] (.RSTB ( RESETn ) , .D ( data_in_02[1] ) 
    , .CLK ( CLK ) , .Q ( frac_02[1] ) ) ;
DFFARX1_RVT \expo_01_reg[2] (.RSTB ( RESETn ) , .D ( data_in_01[12] ) 
    , .CLK ( CLK ) , .Q ( expo_01[2] ) ) ;
DFFARX1_RVT \expo_01_reg[1] (.RSTB ( RESETn ) , .D ( data_in_01[11] ) 
    , .CLK ( CLK ) , .Q ( expo_01[1] ) ) ;
DFFARX1_RVT \expo_01_reg[0] (.RSTB ( RESETn ) , .D ( data_in_01[10] ) 
    , .CLK ( CLK ) , .Q ( expo_01[0] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][15] (.RSTB ( RESETn ) , .D ( data_in_03[15] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][15] ) ) ;
DFFX1_RVT \data_buffer_reg[1][15] (.D ( n75 ) , .CLK ( CLK ) , .Q ( n17 ) ) ;
DFFX1_RVT \data_buffer_reg[2][15] (.D ( n74 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[15] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][14] (.RSTB ( RESETn ) , .D ( data_in_03[14] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][14] ) ) ;
DFFX1_RVT \data_buffer_reg[1][14] (.D ( n73 ) , .CLK ( CLK ) , .Q ( n18 ) ) ;
DFFX1_RVT \data_buffer_reg[2][14] (.D ( n72 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[14] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][13] (.RSTB ( RESETn ) , .D ( data_in_03[13] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][13] ) ) ;
DFFX1_RVT \data_buffer_reg[1][13] (.D ( n71 ) , .CLK ( CLK ) , .Q ( n19 ) ) ;
DFFX1_RVT \data_buffer_reg[2][13] (.D ( n70 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[13] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][12] (.RSTB ( RESETn ) , .D ( data_in_03[12] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][12] ) ) ;
DFFX1_RVT \data_buffer_reg[1][12] (.D ( n69 ) , .CLK ( CLK ) , .Q ( n20 ) ) ;
DFFX1_RVT \data_buffer_reg[2][12] (.D ( n68 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[12] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][11] (.RSTB ( RESETn ) , .D ( data_in_03[11] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][11] ) ) ;
DFFX1_RVT \data_buffer_reg[1][11] (.D ( n67 ) , .CLK ( CLK ) , .Q ( n21 ) ) ;
DFFX1_RVT \data_buffer_reg[2][11] (.D ( n66 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[11] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][10] (.RSTB ( RESETn ) , .D ( data_in_03[10] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][10] ) ) ;
DFFX1_RVT \data_buffer_reg[1][10] (.D ( n65 ) , .CLK ( CLK ) , .Q ( n28 ) ) ;
DFFX1_RVT \data_buffer_reg[2][10] (.D ( n64 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[10] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][9] (.RSTB ( RESETn ) , .D ( data_in_03[9] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][9] ) ) ;
DFFX1_RVT \data_buffer_reg[1][9] (.D ( n63 ) , .CLK ( CLK ) , .Q ( n29 ) ) ;
DFFX1_RVT \data_buffer_reg[2][9] (.D ( n62 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[9] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][8] (.RSTB ( RESETn ) , .D ( data_in_03[8] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][8] ) ) ;
DFFX1_RVT \data_buffer_reg[1][8] (.D ( n61 ) , .CLK ( CLK ) , .Q ( n30 ) ) ;
DFFX1_RVT \data_buffer_reg[2][8] (.D ( n60 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[8] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][7] (.RSTB ( RESETn ) , .D ( data_in_03[7] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][7] ) ) ;
DFFX1_RVT \data_buffer_reg[1][7] (.D ( n59 ) , .CLK ( CLK ) , .Q ( n31 ) ) ;
DFFX1_RVT \data_buffer_reg[2][7] (.D ( n58 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[7] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][6] (.RSTB ( RESETn ) , .D ( data_in_03[6] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][6] ) ) ;
DFFX1_RVT \data_buffer_reg[1][6] (.D ( n57 ) , .CLK ( CLK ) , .Q ( n32 ) ) ;
DFFX1_RVT \data_buffer_reg[2][6] (.D ( n56 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[6] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][5] (.RSTB ( RESETn ) , .D ( data_in_03[5] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][5] ) ) ;
DFFX1_RVT \data_buffer_reg[1][5] (.D ( n55 ) , .CLK ( CLK ) , .Q ( n33 ) ) ;
DFFX1_RVT \data_buffer_reg[2][5] (.D ( n54 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[5] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][4] (.RSTB ( RESETn ) , .D ( data_in_03[4] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][4] ) ) ;
DFFX1_RVT \data_buffer_reg[1][4] (.D ( n53 ) , .CLK ( CLK ) , .Q ( n34 ) ) ;
DFFX1_RVT \data_buffer_reg[2][4] (.D ( n52 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[4] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][3] (.RSTB ( RESETn ) , .D ( data_in_03[3] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][3] ) ) ;
DFFX1_RVT \data_buffer_reg[1][3] (.D ( n51 ) , .CLK ( CLK ) , .Q ( n35 ) ) ;
DFFX1_RVT \data_buffer_reg[2][3] (.D ( n50 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[3] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][2] (.RSTB ( RESETn ) , .D ( data_in_03[2] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][2] ) ) ;
DFFX1_RVT \data_buffer_reg[1][2] (.D ( n49 ) , .CLK ( CLK ) , .Q ( n36 ) ) ;
DFFX1_RVT \data_buffer_reg[2][2] (.D ( n48 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[2] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][1] (.RSTB ( RESETn ) , .D ( data_in_03[1] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][1] ) ) ;
DFFX1_RVT \data_buffer_reg[1][1] (.D ( n47 ) , .CLK ( CLK ) , .Q ( n37 ) ) ;
DFFX1_RVT \data_buffer_reg[2][1] (.D ( n46 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[1] ) ) ;
DFFARX1_RVT \data_buffer_reg[0][0] (.RSTB ( RESETn ) , .D ( data_in_03[0] ) 
    , .CLK ( CLK ) , .Q ( \data_buffer[0][0] ) ) ;
DFFX1_RVT \data_buffer_reg[1][0] (.D ( n45 ) , .CLK ( CLK ) , .Q ( n38 ) ) ;
DFFX1_RVT \data_buffer_reg[2][0] (.D ( n44 ) , .CLK ( CLK ) 
    , .Q ( data_out_03[0] ) ) ;
AO22X1_RVT U3 (.A2 ( n38 ) , .A3 ( n3 ) , .Y ( n44 ) , .A4 ( data_out_03[0] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U4 (.A2 ( \data_buffer[0][0] ) , .A3 ( n3 ) , .Y ( n45 ) , .A4 ( n38 ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U6 (.A2 ( n37 ) , .A3 ( n3 ) , .Y ( n46 ) , .A4 ( data_out_03[1] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U7 (.A2 ( \data_buffer[0][1] ) , .A3 ( n3 ) , .Y ( n47 ) , .A4 ( n37 ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U9 (.A2 ( n36 ) , .A3 ( n3 ) , .Y ( n48 ) , .A4 ( data_out_03[2] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U10 (.A2 ( \data_buffer[0][2] ) , .A3 ( n3 ) , .Y ( n49 ) 
    , .A4 ( n36 ) , .A1 ( RESETn ) ) ;
AO22X1_RVT U12 (.A2 ( n35 ) , .A3 ( n3 ) , .Y ( n50 ) , .A4 ( data_out_03[3] ) 
    , .A1 ( RESETn ) ) ;
AO22X1_RVT U13 (.A2 ( \data_buffer[0][3] ) , .A3 ( n3 ) , .Y ( n51 ) 
    , .A4 ( n35 ) , .A1 ( RESETn ) ) ;
endmodule




module floating_MAC_16 (data_in_A , data_in_B , data_in_C , data_out , 
    RESETn , CLK );
input  [15:0] data_in_A ;
input  [15:0] data_in_B ;
input  [15:0] data_in_C ;
output [15:0] data_out ;
input  RESETn ;
input  CLK ;

wire [15:0] data_out_C ;
wire [16:0] data_out_mul ;



floating_add_16 ADD (.data_out ( data_out ) , .CLK ( CLK ) , 
    .RESETn ( RESETn ) , .sign_in ( sign ) , .data_in_02 ( data_out_C ) , 
    .data_in_01 ( {1'b0, data_out_mul[15] , data_out_mul[14] , data_out_mul[13] , 
	data_out_mul[12] , data_out_mul[11] , data_out_mul[10] , 
	data_out_mul[9] , data_out_mul[8] , data_out_mul[7] , data_out_mul[6] , 
	data_out_mul[5] , data_out_mul[4] , data_out_mul[3] , data_out_mul[2] , 
	data_out_mul[1] , data_out_mul[0] } ) ) ;


floating_mul_16 MUL (.data_out_03 ( data_out_C ) , .CLK ( CLK ) , 
    .RESETn ( RESETn ) , .sign_out ( sign ) , 
    .data_out ( {SYNOPSYS_UNCONNECTED_10, data_out_mul[15] , data_out_mul[14] , 
	data_out_mul[13] , data_out_mul[12] , data_out_mul[11] , 
	data_out_mul[10] , data_out_mul[9] , data_out_mul[8] , 
	data_out_mul[7] , data_out_mul[6] , data_out_mul[5] , data_out_mul[4] , 
	data_out_mul[3] , data_out_mul[2] , data_out_mul[1] , data_out_mul[0] } ) , 
    .data_in_03 ( data_in_C ) , .data_in_02 ( data_in_B ) , 
    .data_in_01 ( data_in_A ) ) ;

endmodule


